/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Streaming App API
 * API for streaming application with WebSocket support
 * OpenAPI spec version: 1.0
 */

import type {
	DataTag,
	DefinedInitialDataOptions,
	DefinedUseInfiniteQueryResult,
	DefinedUseQueryResult,
	InfiniteData,
	QueryClient,
	QueryFunction,
	QueryKey,
	UndefinedInitialDataOptions,
	UseInfiniteQueryOptions,
	UseInfiniteQueryResult,
	UseQueryOptions,
	UseQueryResult,
} from "@tanstack/react-query";
import { useInfiniteQuery, useQuery } from "@tanstack/react-query";

import { customInstance } from "../../client";

/**
 * Establishes a WebSocket connection
 * @summary WebSocket connection
 */
export const getWebsocket = (signal?: AbortSignal) => {
	return customInstance<unknown>({ url: `/websocket`, method: "GET", signal });
};

export const getGetWebsocketInfiniteQueryKey = () => {
	return ["infinate", `/websocket`] as const;
};

export const getGetWebsocketQueryKey = () => {
	return [`/websocket`] as const;
};

export const getGetWebsocketInfiniteQueryOptions = <
	TData = InfiniteData<Awaited<ReturnType<typeof getWebsocket>>>,
	TError = string,
>(options?: {
	query?: Partial<
		UseInfiniteQueryOptions<
			Awaited<ReturnType<typeof getWebsocket>>,
			TError,
			TData
		>
	>;
}) => {
	const { query: queryOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getGetWebsocketInfiniteQueryKey();

	const queryFn: QueryFunction<Awaited<ReturnType<typeof getWebsocket>>> = ({
		signal,
	}) => getWebsocket(signal);

	return {
		queryKey,
		queryFn,
		staleTime: 10000,
		...queryOptions,
	} as UseInfiniteQueryOptions<
		Awaited<ReturnType<typeof getWebsocket>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetWebsocketInfiniteQueryResult = NonNullable<
	Awaited<ReturnType<typeof getWebsocket>>
>;
export type GetWebsocketInfiniteQueryError = string;

export function useGetWebsocketInfinite<
	TData = InfiniteData<Awaited<ReturnType<typeof getWebsocket>>>,
	TError = string,
>(
	options: {
		query: Partial<
			UseInfiniteQueryOptions<
				Awaited<ReturnType<typeof getWebsocket>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getWebsocket>>,
					TError,
					Awaited<ReturnType<typeof getWebsocket>>
				>,
				"initialData"
			>;
	},
	queryClient?: QueryClient,
): DefinedUseInfiniteQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetWebsocketInfinite<
	TData = InfiniteData<Awaited<ReturnType<typeof getWebsocket>>>,
	TError = string,
>(
	options?: {
		query?: Partial<
			UseInfiniteQueryOptions<
				Awaited<ReturnType<typeof getWebsocket>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getWebsocket>>,
					TError,
					Awaited<ReturnType<typeof getWebsocket>>
				>,
				"initialData"
			>;
	},
	queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetWebsocketInfinite<
	TData = InfiniteData<Awaited<ReturnType<typeof getWebsocket>>>,
	TError = string,
>(
	options?: {
		query?: Partial<
			UseInfiniteQueryOptions<
				Awaited<ReturnType<typeof getWebsocket>>,
				TError,
				TData
			>
		>;
	},
	queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary WebSocket connection
 */

export function useGetWebsocketInfinite<
	TData = InfiniteData<Awaited<ReturnType<typeof getWebsocket>>>,
	TError = string,
>(
	options?: {
		query?: Partial<
			UseInfiniteQueryOptions<
				Awaited<ReturnType<typeof getWebsocket>>,
				TError,
				TData
			>
		>;
	},
	queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetWebsocketInfiniteQueryOptions(options);

	const query = useInfiniteQuery(
		queryOptions,
		queryClient,
	) as UseInfiniteQueryResult<TData, TError> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};

	query.queryKey = queryOptions.queryKey;

	return query;
}

export const getGetWebsocketQueryOptions = <
	TData = Awaited<ReturnType<typeof getWebsocket>>,
	TError = string,
>(options?: {
	query?: Partial<
		UseQueryOptions<Awaited<ReturnType<typeof getWebsocket>>, TError, TData>
	>;
}) => {
	const { query: queryOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getGetWebsocketQueryKey();

	const queryFn: QueryFunction<Awaited<ReturnType<typeof getWebsocket>>> = ({
		signal,
	}) => getWebsocket(signal);

	return {
		queryKey,
		queryFn,
		staleTime: 10000,
		...queryOptions,
	} as UseQueryOptions<
		Awaited<ReturnType<typeof getWebsocket>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetWebsocketQueryResult = NonNullable<
	Awaited<ReturnType<typeof getWebsocket>>
>;
export type GetWebsocketQueryError = string;

export function useGetWebsocket<
	TData = Awaited<ReturnType<typeof getWebsocket>>,
	TError = string,
>(
	options: {
		query: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getWebsocket>>, TError, TData>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getWebsocket>>,
					TError,
					Awaited<ReturnType<typeof getWebsocket>>
				>,
				"initialData"
			>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetWebsocket<
	TData = Awaited<ReturnType<typeof getWebsocket>>,
	TError = string,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getWebsocket>>, TError, TData>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getWebsocket>>,
					TError,
					Awaited<ReturnType<typeof getWebsocket>>
				>,
				"initialData"
			>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetWebsocket<
	TData = Awaited<ReturnType<typeof getWebsocket>>,
	TError = string,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getWebsocket>>, TError, TData>
		>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary WebSocket connection
 */

export function useGetWebsocket<
	TData = Awaited<ReturnType<typeof getWebsocket>>,
	TError = string,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getWebsocket>>, TError, TData>
		>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetWebsocketQueryOptions(options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	query.queryKey = queryOptions.queryKey;

	return query;
}
