/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Streaming App API
 * API for streaming application with WebSocket support
 * OpenAPI spec version: 1.0
 */

import type {
	DataTag,
	DefinedInitialDataOptions,
	DefinedUseInfiniteQueryResult,
	DefinedUseQueryResult,
	InfiniteData,
	MutationFunction,
	QueryClient,
	QueryFunction,
	QueryKey,
	UndefinedInitialDataOptions,
	UseInfiniteQueryOptions,
	UseInfiniteQueryResult,
	UseMutationOptions,
	UseMutationResult,
	UseQueryOptions,
	UseQueryResult,
} from "@tanstack/react-query";
import { useInfiniteQuery, useMutation, useQuery } from "@tanstack/react-query";
import { customInstance } from "../../client";
import type {
	GetUsersMeWatchlist200,
	GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse,
	GithubComTeachiesStreamingApInternalDatabaseModelsApiSuccessResponse,
} from "../../models";

/**
 * Retrieves full movie details (Title, Poster, Rating, etc.) for all movies in the authenticated user's watchlist using a high-performance Elasticsearch terms lookup.
 * @summary Get user's watchlist
 */
export const getUsersMeWatchlist = (signal?: AbortSignal) => {
	return customInstance<GetUsersMeWatchlist200>({
		url: `/users/me/watchlist`,
		method: "GET",
		signal,
	});
};

export const getGetUsersMeWatchlistInfiniteQueryKey = () => {
	return ["infinate", `/users/me/watchlist`] as const;
};

export const getGetUsersMeWatchlistQueryKey = () => {
	return [`/users/me/watchlist`] as const;
};

export const getGetUsersMeWatchlistInfiniteQueryOptions = <
	TData = InfiniteData<Awaited<ReturnType<typeof getUsersMeWatchlist>>>,
	TError =
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse,
>(options?: {
	query?: Partial<
		UseInfiniteQueryOptions<
			Awaited<ReturnType<typeof getUsersMeWatchlist>>,
			TError,
			TData
		>
	>;
}) => {
	const { query: queryOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ?? getGetUsersMeWatchlistInfiniteQueryKey();

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof getUsersMeWatchlist>>
	> = ({ signal }) => getUsersMeWatchlist(signal);

	return {
		queryKey,
		queryFn,
		staleTime: 10000,
		...queryOptions,
	} as UseInfiniteQueryOptions<
		Awaited<ReturnType<typeof getUsersMeWatchlist>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetUsersMeWatchlistInfiniteQueryResult = NonNullable<
	Awaited<ReturnType<typeof getUsersMeWatchlist>>
>;
export type GetUsersMeWatchlistInfiniteQueryError =
	| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse
	| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse;

export function useGetUsersMeWatchlistInfinite<
	TData = InfiniteData<Awaited<ReturnType<typeof getUsersMeWatchlist>>>,
	TError =
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse,
>(
	options: {
		query: Partial<
			UseInfiniteQueryOptions<
				Awaited<ReturnType<typeof getUsersMeWatchlist>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getUsersMeWatchlist>>,
					TError,
					Awaited<ReturnType<typeof getUsersMeWatchlist>>
				>,
				"initialData"
			>;
	},
	queryClient?: QueryClient,
): DefinedUseInfiniteQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetUsersMeWatchlistInfinite<
	TData = InfiniteData<Awaited<ReturnType<typeof getUsersMeWatchlist>>>,
	TError =
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse,
>(
	options?: {
		query?: Partial<
			UseInfiniteQueryOptions<
				Awaited<ReturnType<typeof getUsersMeWatchlist>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getUsersMeWatchlist>>,
					TError,
					Awaited<ReturnType<typeof getUsersMeWatchlist>>
				>,
				"initialData"
			>;
	},
	queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetUsersMeWatchlistInfinite<
	TData = InfiniteData<Awaited<ReturnType<typeof getUsersMeWatchlist>>>,
	TError =
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse,
>(
	options?: {
		query?: Partial<
			UseInfiniteQueryOptions<
				Awaited<ReturnType<typeof getUsersMeWatchlist>>,
				TError,
				TData
			>
		>;
	},
	queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get user's watchlist
 */

export function useGetUsersMeWatchlistInfinite<
	TData = InfiniteData<Awaited<ReturnType<typeof getUsersMeWatchlist>>>,
	TError =
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse,
>(
	options?: {
		query?: Partial<
			UseInfiniteQueryOptions<
				Awaited<ReturnType<typeof getUsersMeWatchlist>>,
				TError,
				TData
			>
		>;
	},
	queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetUsersMeWatchlistInfiniteQueryOptions(options);

	const query = useInfiniteQuery(
		queryOptions,
		queryClient,
	) as UseInfiniteQueryResult<TData, TError> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};

	query.queryKey = queryOptions.queryKey;

	return query;
}

export const getGetUsersMeWatchlistQueryOptions = <
	TData = Awaited<ReturnType<typeof getUsersMeWatchlist>>,
	TError =
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse,
>(options?: {
	query?: Partial<
		UseQueryOptions<
			Awaited<ReturnType<typeof getUsersMeWatchlist>>,
			TError,
			TData
		>
	>;
}) => {
	const { query: queryOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getGetUsersMeWatchlistQueryKey();

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof getUsersMeWatchlist>>
	> = ({ signal }) => getUsersMeWatchlist(signal);

	return {
		queryKey,
		queryFn,
		staleTime: 10000,
		...queryOptions,
	} as UseQueryOptions<
		Awaited<ReturnType<typeof getUsersMeWatchlist>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetUsersMeWatchlistQueryResult = NonNullable<
	Awaited<ReturnType<typeof getUsersMeWatchlist>>
>;
export type GetUsersMeWatchlistQueryError =
	| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse
	| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse;

export function useGetUsersMeWatchlist<
	TData = Awaited<ReturnType<typeof getUsersMeWatchlist>>,
	TError =
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse,
>(
	options: {
		query: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getUsersMeWatchlist>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getUsersMeWatchlist>>,
					TError,
					Awaited<ReturnType<typeof getUsersMeWatchlist>>
				>,
				"initialData"
			>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetUsersMeWatchlist<
	TData = Awaited<ReturnType<typeof getUsersMeWatchlist>>,
	TError =
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getUsersMeWatchlist>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getUsersMeWatchlist>>,
					TError,
					Awaited<ReturnType<typeof getUsersMeWatchlist>>
				>,
				"initialData"
			>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetUsersMeWatchlist<
	TData = Awaited<ReturnType<typeof getUsersMeWatchlist>>,
	TError =
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getUsersMeWatchlist>>,
				TError,
				TData
			>
		>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get user's watchlist
 */

export function useGetUsersMeWatchlist<
	TData = Awaited<ReturnType<typeof getUsersMeWatchlist>>,
	TError =
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getUsersMeWatchlist>>,
				TError,
				TData
			>
		>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetUsersMeWatchlistQueryOptions(options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	query.queryKey = queryOptions.queryKey;

	return query;
}

/**
 * Adds a specified movie (by IMDb ID) to the authenticated user's unique watchlist.
 * @summary Add movie to user's watchlist
 */
export const postUsersMeWatchlistImdbId = (
	imdbId: string,
	signal?: AbortSignal,
) => {
	return customInstance<GithubComTeachiesStreamingApInternalDatabaseModelsApiSuccessResponse>(
		{ url: `/users/me/watchlist/${imdbId}`, method: "POST", signal },
	);
};

export const getPostUsersMeWatchlistImdbIdMutationOptions = <
	TError =
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof postUsersMeWatchlistImdbId>>,
		TError,
		{ imdbId: string },
		TContext
	>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof postUsersMeWatchlistImdbId>>,
	TError,
	{ imdbId: string },
	TContext
> => {
	const mutationKey = ["postUsersMeWatchlistImdbId"];
	const { mutation: mutationOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey } };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof postUsersMeWatchlistImdbId>>,
		{ imdbId: string }
	> = (props) => {
		const { imdbId } = props ?? {};

		return postUsersMeWatchlistImdbId(imdbId);
	};

	return { mutationFn, ...mutationOptions };
};

export type PostUsersMeWatchlistImdbIdMutationResult = NonNullable<
	Awaited<ReturnType<typeof postUsersMeWatchlistImdbId>>
>;

export type PostUsersMeWatchlistImdbIdMutationError =
	| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse
	| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse
	| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse;

/**
 * @summary Add movie to user's watchlist
 */
export const usePostUsersMeWatchlistImdbId = <
	TError =
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof postUsersMeWatchlistImdbId>>,
			TError,
			{ imdbId: string },
			TContext
		>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof postUsersMeWatchlistImdbId>>,
	TError,
	{ imdbId: string },
	TContext
> => {
	const mutationOptions = getPostUsersMeWatchlistImdbIdMutationOptions(options);

	return useMutation(mutationOptions, queryClient);
};
/**
 * Removes a specified movie (by IMDb ID) from the authenticated user's watchlist.
 * @summary Remove movie from user's watchlist
 */
export const deleteUsersMeWatchlistImdbId = (imdbId: string) => {
	return customInstance<GithubComTeachiesStreamingApInternalDatabaseModelsApiSuccessResponse>(
		{ url: `/users/me/watchlist/${imdbId}`, method: "DELETE" },
	);
};

export const getDeleteUsersMeWatchlistImdbIdMutationOptions = <
	TError =
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof deleteUsersMeWatchlistImdbId>>,
		TError,
		{ imdbId: string },
		TContext
	>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof deleteUsersMeWatchlistImdbId>>,
	TError,
	{ imdbId: string },
	TContext
> => {
	const mutationKey = ["deleteUsersMeWatchlistImdbId"];
	const { mutation: mutationOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey } };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof deleteUsersMeWatchlistImdbId>>,
		{ imdbId: string }
	> = (props) => {
		const { imdbId } = props ?? {};

		return deleteUsersMeWatchlistImdbId(imdbId);
	};

	return { mutationFn, ...mutationOptions };
};

export type DeleteUsersMeWatchlistImdbIdMutationResult = NonNullable<
	Awaited<ReturnType<typeof deleteUsersMeWatchlistImdbId>>
>;

export type DeleteUsersMeWatchlistImdbIdMutationError =
	| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse
	| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse;

/**
 * @summary Remove movie from user's watchlist
 */
export const useDeleteUsersMeWatchlistImdbId = <
	TError =
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof deleteUsersMeWatchlistImdbId>>,
			TError,
			{ imdbId: string },
			TContext
		>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof deleteUsersMeWatchlistImdbId>>,
	TError,
	{ imdbId: string },
	TContext
> => {
	const mutationOptions =
		getDeleteUsersMeWatchlistImdbIdMutationOptions(options);

	return useMutation(mutationOptions, queryClient);
};
