/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Streaming App API
 * API for streaming application with WebSocket support
 * OpenAPI spec version: 1.0
 */

import type {
	MutationFunction,
	QueryClient,
	UseMutationOptions,
	UseMutationResult,
} from "@tanstack/react-query";
import { useMutation } from "@tanstack/react-query";
import { customInstance } from "../../client";
import type {
	GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse,
	GithubComTeachiesStreamingApInternalDatabaseModelsApiSuccessResponse,
	GithubComTeachiesStreamingApInternalDatabaseModelsPasswordResetReq,
	GithubComTeachiesStreamingApInternalDatabaseModelsUserLogging,
	GithubComTeachiesStreamingApInternalDatabaseModelsUserRegister,
} from "../../models";

/**
 * Authenticates a user and returns access and refresh tokens
 * @summary User Login
 */
export const postAuthLogin = (
	githubComTeachiesStreamingApInternalDatabaseModelsUserLogging: GithubComTeachiesStreamingApInternalDatabaseModelsUserLogging,
	signal?: AbortSignal,
) => {
	return customInstance<GithubComTeachiesStreamingApInternalDatabaseModelsApiSuccessResponse>(
		{
			url: `/auth/login`,
			method: "POST",
			headers: { "Content-Type": "application/json" },
			data: githubComTeachiesStreamingApInternalDatabaseModelsUserLogging,
			signal,
		},
	);
};

export const getPostAuthLoginMutationOptions = <
	TError =
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof postAuthLogin>>,
		TError,
		{ data: GithubComTeachiesStreamingApInternalDatabaseModelsUserLogging },
		TContext
	>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof postAuthLogin>>,
	TError,
	{ data: GithubComTeachiesStreamingApInternalDatabaseModelsUserLogging },
	TContext
> => {
	const mutationKey = ["postAuthLogin"];
	const { mutation: mutationOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey } };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof postAuthLogin>>,
		{ data: GithubComTeachiesStreamingApInternalDatabaseModelsUserLogging }
	> = (props) => {
		const { data } = props ?? {};

		return postAuthLogin(data);
	};

	return { mutationFn, ...mutationOptions };
};

export type PostAuthLoginMutationResult = NonNullable<
	Awaited<ReturnType<typeof postAuthLogin>>
>;
export type PostAuthLoginMutationBody =
	GithubComTeachiesStreamingApInternalDatabaseModelsUserLogging;
export type PostAuthLoginMutationError =
	| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse
	| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse
	| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse;

/**
 * @summary User Login
 */
export const usePostAuthLogin = <
	TError =
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof postAuthLogin>>,
			TError,
			{ data: GithubComTeachiesStreamingApInternalDatabaseModelsUserLogging },
			TContext
		>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof postAuthLogin>>,
	TError,
	{ data: GithubComTeachiesStreamingApInternalDatabaseModelsUserLogging },
	TContext
> => {
	const mutationOptions = getPostAuthLoginMutationOptions(options);

	return useMutation(mutationOptions, queryClient);
};
/**
 * Invalidates the user's session by clearing tokens from the database.
 * @summary User Logout
 */
export const postAuthLogout = (signal?: AbortSignal) => {
	return customInstance<GithubComTeachiesStreamingApInternalDatabaseModelsApiSuccessResponse>(
		{ url: `/auth/logout`, method: "POST", signal },
	);
};

export const getPostAuthLogoutMutationOptions = <
	TError =
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof postAuthLogout>>,
		TError,
		void,
		TContext
	>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof postAuthLogout>>,
	TError,
	void,
	TContext
> => {
	const mutationKey = ["postAuthLogout"];
	const { mutation: mutationOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey } };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof postAuthLogout>>,
		void
	> = () => {
		return postAuthLogout();
	};

	return { mutationFn, ...mutationOptions };
};

export type PostAuthLogoutMutationResult = NonNullable<
	Awaited<ReturnType<typeof postAuthLogout>>
>;

export type PostAuthLogoutMutationError =
	| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse
	| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse;

/**
 * @summary User Logout
 */
export const usePostAuthLogout = <
	TError =
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof postAuthLogout>>,
			TError,
			void,
			TContext
		>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof postAuthLogout>>,
	TError,
	void,
	TContext
> => {
	const mutationOptions = getPostAuthLogoutMutationOptions(options);

	return useMutation(mutationOptions, queryClient);
};
/**
 * Creates a new user account with hashed password and metadata.
 * @summary Register a new user
 */
export const postAuthRegister = (
	githubComTeachiesStreamingApInternalDatabaseModelsUserRegister: GithubComTeachiesStreamingApInternalDatabaseModelsUserRegister,
	signal?: AbortSignal,
) => {
	return customInstance<GithubComTeachiesStreamingApInternalDatabaseModelsApiSuccessResponse>(
		{
			url: `/auth/register`,
			method: "POST",
			headers: { "Content-Type": "application/json" },
			data: githubComTeachiesStreamingApInternalDatabaseModelsUserRegister,
			signal,
		},
	);
};

export const getPostAuthRegisterMutationOptions = <
	TError =
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof postAuthRegister>>,
		TError,
		{ data: GithubComTeachiesStreamingApInternalDatabaseModelsUserRegister },
		TContext
	>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof postAuthRegister>>,
	TError,
	{ data: GithubComTeachiesStreamingApInternalDatabaseModelsUserRegister },
	TContext
> => {
	const mutationKey = ["postAuthRegister"];
	const { mutation: mutationOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey } };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof postAuthRegister>>,
		{ data: GithubComTeachiesStreamingApInternalDatabaseModelsUserRegister }
	> = (props) => {
		const { data } = props ?? {};

		return postAuthRegister(data);
	};

	return { mutationFn, ...mutationOptions };
};

export type PostAuthRegisterMutationResult = NonNullable<
	Awaited<ReturnType<typeof postAuthRegister>>
>;
export type PostAuthRegisterMutationBody =
	GithubComTeachiesStreamingApInternalDatabaseModelsUserRegister;
export type PostAuthRegisterMutationError =
	| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse
	| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse
	| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse;

/**
 * @summary Register a new user
 */
export const usePostAuthRegister = <
	TError =
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof postAuthRegister>>,
			TError,
			{ data: GithubComTeachiesStreamingApInternalDatabaseModelsUserRegister },
			TContext
		>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof postAuthRegister>>,
	TError,
	{ data: GithubComTeachiesStreamingApInternalDatabaseModelsUserRegister },
	TContext
> => {
	const mutationOptions = getPostAuthRegisterMutationOptions(options);

	return useMutation(mutationOptions, queryClient);
};
/**
 * Allows an authenticated user to change their password by verifying the old one.
 * @summary Reset user password
 */
export const postAuthResetPassword = (
	githubComTeachiesStreamingApInternalDatabaseModelsPasswordResetReq: GithubComTeachiesStreamingApInternalDatabaseModelsPasswordResetReq,
	signal?: AbortSignal,
) => {
	return customInstance<GithubComTeachiesStreamingApInternalDatabaseModelsApiSuccessResponse>(
		{
			url: `/auth/reset-password`,
			method: "POST",
			headers: { "Content-Type": "application/json" },
			data: githubComTeachiesStreamingApInternalDatabaseModelsPasswordResetReq,
			signal,
		},
	);
};

export const getPostAuthResetPasswordMutationOptions = <
	TError =
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof postAuthResetPassword>>,
		TError,
		{
			data: GithubComTeachiesStreamingApInternalDatabaseModelsPasswordResetReq;
		},
		TContext
	>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof postAuthResetPassword>>,
	TError,
	{ data: GithubComTeachiesStreamingApInternalDatabaseModelsPasswordResetReq },
	TContext
> => {
	const mutationKey = ["postAuthResetPassword"];
	const { mutation: mutationOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey } };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof postAuthResetPassword>>,
		{ data: GithubComTeachiesStreamingApInternalDatabaseModelsPasswordResetReq }
	> = (props) => {
		const { data } = props ?? {};

		return postAuthResetPassword(data);
	};

	return { mutationFn, ...mutationOptions };
};

export type PostAuthResetPasswordMutationResult = NonNullable<
	Awaited<ReturnType<typeof postAuthResetPassword>>
>;
export type PostAuthResetPasswordMutationBody =
	GithubComTeachiesStreamingApInternalDatabaseModelsPasswordResetReq;
export type PostAuthResetPasswordMutationError =
	| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse
	| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse
	| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse;

/**
 * @summary Reset user password
 */
export const usePostAuthResetPassword = <
	TError =
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof postAuthResetPassword>>,
			TError,
			{
				data: GithubComTeachiesStreamingApInternalDatabaseModelsPasswordResetReq;
			},
			TContext
		>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof postAuthResetPassword>>,
	TError,
	{ data: GithubComTeachiesStreamingApInternalDatabaseModelsPasswordResetReq },
	TContext
> => {
	const mutationOptions = getPostAuthResetPasswordMutationOptions(options);

	return useMutation(mutationOptions, queryClient);
};
