/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Streaming App API
 * API for streaming application with WebSocket support
 * OpenAPI spec version: 1.0
 */

import type {
	MutationFunction,
	QueryClient,
	UseMutationOptions,
	UseMutationResult,
} from "@tanstack/react-query";
import { useMutation } from "@tanstack/react-query";
import { customInstance } from "../../client";
import type {
	InternalApiControllersUsersOnboardingRequest,
	PostUserOnboarding200,
} from "../../models";

/**
 * @summary Save user genre preferences during onboarding
 */
export const postUserOnboarding = (
	internalApiControllersUsersOnboardingRequest: InternalApiControllersUsersOnboardingRequest,
	signal?: AbortSignal,
) => {
	return customInstance<PostUserOnboarding200>({
		url: `/user/onboarding`,
		method: "POST",
		headers: { "Content-Type": "application/json" },
		data: internalApiControllersUsersOnboardingRequest,
		signal,
	});
};

export const getPostUserOnboardingMutationOptions = <
	TError = unknown,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof postUserOnboarding>>,
		TError,
		{ data: InternalApiControllersUsersOnboardingRequest },
		TContext
	>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof postUserOnboarding>>,
	TError,
	{ data: InternalApiControllersUsersOnboardingRequest },
	TContext
> => {
	const mutationKey = ["postUserOnboarding"];
	const { mutation: mutationOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey } };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof postUserOnboarding>>,
		{ data: InternalApiControllersUsersOnboardingRequest }
	> = (props) => {
		const { data } = props ?? {};

		return postUserOnboarding(data);
	};

	return { mutationFn, ...mutationOptions };
};

export type PostUserOnboardingMutationResult = NonNullable<
	Awaited<ReturnType<typeof postUserOnboarding>>
>;
export type PostUserOnboardingMutationBody =
	InternalApiControllersUsersOnboardingRequest;
export type PostUserOnboardingMutationError = unknown;

/**
 * @summary Save user genre preferences during onboarding
 */
export const usePostUserOnboarding = <TError = unknown, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof postUserOnboarding>>,
			TError,
			{ data: InternalApiControllersUsersOnboardingRequest },
			TContext
		>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof postUserOnboarding>>,
	TError,
	{ data: InternalApiControllersUsersOnboardingRequest },
	TContext
> => {
	const mutationOptions = getPostUserOnboardingMutationOptions(options);

	return useMutation(mutationOptions, queryClient);
};
