/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Streaming App API
 * API for streaming application with WebSocket support
 * OpenAPI spec version: 1.0
 */

import type {
	DataTag,
	DefinedInitialDataOptions,
	DefinedUseInfiniteQueryResult,
	DefinedUseQueryResult,
	InfiniteData,
	MutationFunction,
	QueryClient,
	QueryFunction,
	QueryKey,
	UndefinedInitialDataOptions,
	UseInfiniteQueryOptions,
	UseInfiniteQueryResult,
	UseMutationOptions,
	UseMutationResult,
	UseQueryOptions,
	UseQueryResult,
} from "@tanstack/react-query";
import { useInfiniteQuery, useMutation, useQuery } from "@tanstack/react-query";
import { customInstance } from "../../client";
import type {
	GetUsersMeFavorites200,
	GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse,
	GithubComTeachiesStreamingApInternalDatabaseModelsApiSuccessResponse,
} from "../../models";

/**
 * Retrieves full movie details for all movies marked as favorites by the authenticated user.
 * @summary Get user's favorite movies
 */
export const getUsersMeFavorites = (signal?: AbortSignal) => {
	return customInstance<GetUsersMeFavorites200>({
		url: `/users/me/favorites`,
		method: "GET",
		signal,
	});
};

export const getGetUsersMeFavoritesInfiniteQueryKey = () => {
	return ["infinate", `/users/me/favorites`] as const;
};

export const getGetUsersMeFavoritesQueryKey = () => {
	return [`/users/me/favorites`] as const;
};

export const getGetUsersMeFavoritesInfiniteQueryOptions = <
	TData = InfiniteData<Awaited<ReturnType<typeof getUsersMeFavorites>>>,
	TError =
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse,
>(options?: {
	query?: Partial<
		UseInfiniteQueryOptions<
			Awaited<ReturnType<typeof getUsersMeFavorites>>,
			TError,
			TData
		>
	>;
}) => {
	const { query: queryOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ?? getGetUsersMeFavoritesInfiniteQueryKey();

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof getUsersMeFavorites>>
	> = ({ signal }) => getUsersMeFavorites(signal);

	return {
		queryKey,
		queryFn,
		staleTime: 10000,
		...queryOptions,
	} as UseInfiniteQueryOptions<
		Awaited<ReturnType<typeof getUsersMeFavorites>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetUsersMeFavoritesInfiniteQueryResult = NonNullable<
	Awaited<ReturnType<typeof getUsersMeFavorites>>
>;
export type GetUsersMeFavoritesInfiniteQueryError =
	| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse
	| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse;

export function useGetUsersMeFavoritesInfinite<
	TData = InfiniteData<Awaited<ReturnType<typeof getUsersMeFavorites>>>,
	TError =
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse,
>(
	options: {
		query: Partial<
			UseInfiniteQueryOptions<
				Awaited<ReturnType<typeof getUsersMeFavorites>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getUsersMeFavorites>>,
					TError,
					Awaited<ReturnType<typeof getUsersMeFavorites>>
				>,
				"initialData"
			>;
	},
	queryClient?: QueryClient,
): DefinedUseInfiniteQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetUsersMeFavoritesInfinite<
	TData = InfiniteData<Awaited<ReturnType<typeof getUsersMeFavorites>>>,
	TError =
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse,
>(
	options?: {
		query?: Partial<
			UseInfiniteQueryOptions<
				Awaited<ReturnType<typeof getUsersMeFavorites>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getUsersMeFavorites>>,
					TError,
					Awaited<ReturnType<typeof getUsersMeFavorites>>
				>,
				"initialData"
			>;
	},
	queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetUsersMeFavoritesInfinite<
	TData = InfiniteData<Awaited<ReturnType<typeof getUsersMeFavorites>>>,
	TError =
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse,
>(
	options?: {
		query?: Partial<
			UseInfiniteQueryOptions<
				Awaited<ReturnType<typeof getUsersMeFavorites>>,
				TError,
				TData
			>
		>;
	},
	queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get user's favorite movies
 */

export function useGetUsersMeFavoritesInfinite<
	TData = InfiniteData<Awaited<ReturnType<typeof getUsersMeFavorites>>>,
	TError =
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse,
>(
	options?: {
		query?: Partial<
			UseInfiniteQueryOptions<
				Awaited<ReturnType<typeof getUsersMeFavorites>>,
				TError,
				TData
			>
		>;
	},
	queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetUsersMeFavoritesInfiniteQueryOptions(options);

	const query = useInfiniteQuery(
		queryOptions,
		queryClient,
	) as UseInfiniteQueryResult<TData, TError> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};

	query.queryKey = queryOptions.queryKey;

	return query;
}

export const getGetUsersMeFavoritesQueryOptions = <
	TData = Awaited<ReturnType<typeof getUsersMeFavorites>>,
	TError =
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse,
>(options?: {
	query?: Partial<
		UseQueryOptions<
			Awaited<ReturnType<typeof getUsersMeFavorites>>,
			TError,
			TData
		>
	>;
}) => {
	const { query: queryOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getGetUsersMeFavoritesQueryKey();

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof getUsersMeFavorites>>
	> = ({ signal }) => getUsersMeFavorites(signal);

	return {
		queryKey,
		queryFn,
		staleTime: 10000,
		...queryOptions,
	} as UseQueryOptions<
		Awaited<ReturnType<typeof getUsersMeFavorites>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetUsersMeFavoritesQueryResult = NonNullable<
	Awaited<ReturnType<typeof getUsersMeFavorites>>
>;
export type GetUsersMeFavoritesQueryError =
	| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse
	| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse;

export function useGetUsersMeFavorites<
	TData = Awaited<ReturnType<typeof getUsersMeFavorites>>,
	TError =
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse,
>(
	options: {
		query: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getUsersMeFavorites>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getUsersMeFavorites>>,
					TError,
					Awaited<ReturnType<typeof getUsersMeFavorites>>
				>,
				"initialData"
			>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetUsersMeFavorites<
	TData = Awaited<ReturnType<typeof getUsersMeFavorites>>,
	TError =
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getUsersMeFavorites>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getUsersMeFavorites>>,
					TError,
					Awaited<ReturnType<typeof getUsersMeFavorites>>
				>,
				"initialData"
			>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetUsersMeFavorites<
	TData = Awaited<ReturnType<typeof getUsersMeFavorites>>,
	TError =
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getUsersMeFavorites>>,
				TError,
				TData
			>
		>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get user's favorite movies
 */

export function useGetUsersMeFavorites<
	TData = Awaited<ReturnType<typeof getUsersMeFavorites>>,
	TError =
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getUsersMeFavorites>>,
				TError,
				TData
			>
		>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetUsersMeFavoritesQueryOptions(options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	query.queryKey = queryOptions.queryKey;

	return query;
}

/**
 * Adds or removes a movie from the user's personal favorites list.
 * @summary Toggle favorite status
 */
export const postUsersMeFavoritesImdbId = (
	imdbId: string,
	signal?: AbortSignal,
) => {
	return customInstance<GithubComTeachiesStreamingApInternalDatabaseModelsApiSuccessResponse>(
		{ url: `/users/me/favorites/${imdbId}`, method: "POST", signal },
	);
};

export const getPostUsersMeFavoritesImdbIdMutationOptions = <
	TError = unknown,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof postUsersMeFavoritesImdbId>>,
		TError,
		{ imdbId: string },
		TContext
	>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof postUsersMeFavoritesImdbId>>,
	TError,
	{ imdbId: string },
	TContext
> => {
	const mutationKey = ["postUsersMeFavoritesImdbId"];
	const { mutation: mutationOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey } };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof postUsersMeFavoritesImdbId>>,
		{ imdbId: string }
	> = (props) => {
		const { imdbId } = props ?? {};

		return postUsersMeFavoritesImdbId(imdbId);
	};

	return { mutationFn, ...mutationOptions };
};

export type PostUsersMeFavoritesImdbIdMutationResult = NonNullable<
	Awaited<ReturnType<typeof postUsersMeFavoritesImdbId>>
>;

export type PostUsersMeFavoritesImdbIdMutationError = unknown;

/**
 * @summary Toggle favorite status
 */
export const usePostUsersMeFavoritesImdbId = <
	TError = unknown,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof postUsersMeFavoritesImdbId>>,
			TError,
			{ imdbId: string },
			TContext
		>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof postUsersMeFavoritesImdbId>>,
	TError,
	{ imdbId: string },
	TContext
> => {
	const mutationOptions = getPostUsersMeFavoritesImdbIdMutationOptions(options);

	return useMutation(mutationOptions, queryClient);
};
