/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Streaming App API
 * API for streaming application with WebSocket support
 * OpenAPI spec version: 1.0
 */

export type GetMoviesParams = {
	/**
	 * Search by title (regex)
	 */
	title?: string;
	/**
	 * Filter by genre name
	 */
	genre?: string;
	/**
	 * Number of results (default 10)
	 */
	limit?: number;
	/**
	 * Page number (default 1)
	 */
	page?: number;
};
