/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Streaming App API
 * API for streaming application with WebSocket support
 * OpenAPI spec version: 1.0
 */

export type GetMoviesSearchParams = {
	/**
	 * Search keywords (matches title and reviews)
	 */
	q: string;
	/**
	 * Filter by specific genre name
	 */
	genre_name?: string;
	/**
	 * Minimum ranking value (1-5)
	 */
	min_ranking?: number;
	/**
	 * Maximum ranking value (1-5)
	 */
	max_ranking?: number;
	/**
	 * Filter by exact IMDB ID
	 */
	imdb_id?: string;
	/**
	 * Page number for pagination (default 1)
	 */
	page?: number;
	/**
	 * Number of results per page (default 10)
	 */
	limit?: number;
	/**
	 * Field to sort by (e.g. 'year')
	 */
	sort_by?: string;
};
