/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Streaming App API
 * API for streaming application with WebSocket support
 * OpenAPI spec version: 1.0
 */

import type { GetUsersMeFavorites200AllOf } from "./getUsersMeFavorites200AllOf";
import type { GithubComTeachiesStreamingApInternalDatabaseModelsApiSuccessResponse } from "./githubComTeachiesStreamingApInternalDatabaseModelsApiSuccessResponse";

export type GetUsersMeFavorites200 =
	GithubComTeachiesStreamingApInternalDatabaseModelsApiSuccessResponse &
		GetUsersMeFavorites200AllOf;
