/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Streaming App API
 * API for streaming application with WebSocket support
 * OpenAPI spec version: 1.0
 */

export type GetUsersParams = {
	/**
	 * Search by email (regex)
	 */
	email?: string;
	/**
	 * Search by first name
	 */
	first_name?: string;
	/**
	 * Search by last name
	 */
	last_name?: string;
	/**
	 * Number of results (default 10)
	 */
	limit?: number;
	/**
	 * Page number (default 1)
	 */
	page?: number;
};
