/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Streaming App API
 * API for streaming application with WebSocket support
 * OpenAPI spec version: 1.0
 */
import type { GithubComTeachiesStreamingApInternalDatabaseModelsGenre } from "./githubComTeachiesStreamingApInternalDatabaseModelsGenre";
import type { GithubComTeachiesStreamingApInternalDatabaseModelsRanking } from "./githubComTeachiesStreamingApInternalDatabaseModelsRanking";

export interface GithubComTeachiesStreamingApInternalDatabaseModelsUpdateMovieRequest {
	admin_review?: string;
	genre?: GithubComTeachiesStreamingApInternalDatabaseModelsGenre[];
	poster_path?: string;
	ranking?: GithubComTeachiesStreamingApInternalDatabaseModelsRanking;
	/**
	 * @minLength 1
	 * @maxLength 555
	 */
	title?: string;
	youtube_id?: string;
}
