/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Streaming App API
 * API for streaming application with WebSocket support
 * OpenAPI spec version: 1.0
 */
import type { GithubComTeachiesStreamingApInternalDatabaseModelsGenre } from "./githubComTeachiesStreamingApInternalDatabaseModelsGenre";
import type { GithubComTeachiesStreamingApInternalDatabaseModelsRanking } from "./githubComTeachiesStreamingApInternalDatabaseModelsRanking";

export interface GithubComTeachiesStreamingApInternalDatabaseModelsMovie {
	/** For wide banners */
	backdrop_path?: string;
	/** Financials */
	budget?: string;
	/** People & Production */
	director?: string;
	/** Technical Stats */
	duration?: string;
	/** Classification */
	genre: GithubComTeachiesStreamingApInternalDatabaseModelsGenre[];
	id?: string;
	imdb_id: string;
	is_trending?: boolean;
	/** When was this updated from IMDB? */
	last_sync_date?: string;
	likes_count?: number;
	/** Metrics & Search-ability */
	metascore?: number;
	/** Current rank in trending */
	popularity?: number;
	/** Up/Down from last week */
	popularity_change?: number;
	/** Media Assets */
	poster_path: string;
	production_co?: string;
	/** AI-based rank */
	ranking: GithubComTeachiesStreamingApInternalDatabaseModelsRanking;
	/** User average rating */
	rating?: number;
	/** PG-13, R, etc. */
	rating_label?: string;
	release_date?: string;
	revenue?: string;
	stars?: string[];
	synopsis?: string;
	/**
	 * @minLength 1
	 * @maxLength 555
	 */
	title: string;
	trailer_url?: string;
	/** Production-Ready suggestions added by Gemini */
	video_quality?: string[];
	/** Number of user votes */
	votes?: number;
	writers?: string[];
	year?: number;
	/** Redundant but useful for API integrations */
	youtube_id?: string;
}
