/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Streaming App API
 * API for streaming application with WebSocket support
 * OpenAPI spec version: 1.0
 */

export interface GithubComTeachiesStreamingApInternalDatabaseModelsUserRegister {
	created_at?: string;
	email: string;
	/** @minLength 6 */
	first_name: string;
	id?: string;
	/** @minLength 6 */
	last_name: string;
	/** @minLength 6 */
	password: string;
	updated_at?: string;
}
