/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Streaming App API
 * API for streaming application with WebSocket support
 * OpenAPI spec version: 1.0
 */

export type ModelsUserRole =
	(typeof ModelsUserRole)[keyof typeof ModelsUserRole];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ModelsUserRole = {
	ADMIN: "ADMIN",
	USER: "USER",
	CUSTOMER: "CUSTOMER",
} as const;
