/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Streaming App API
 * API for streaming application with WebSocket support
 * OpenAPI spec version: 1.0
 */
import type { ModelsGenre } from "./modelsGenre";
import type { ModelsRanking } from "./modelsRanking";

export interface ModelsUpdateMovieRequest {
	admin_review?: string;
	genre?: ModelsGenre[];
	poster_path?: string;
	ranking?: ModelsRanking;
	/**
	 * @minLength 1
	 * @maxLength 555
	 */
	title?: string;
	youtube_id?: string;
}
