/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Streaming App API
 * API for streaming application with WebSocket support
 * OpenAPI spec version: 1.0
 */

export interface ModelsWatchProgress {
	/** Total length */
	duration_seconds?: number;
	imdb_id?: string;
	progress_seconds?: number;
	updated_at?: string;
}
