/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Streaming App API
 * API for streaming application with WebSocket support
 * OpenAPI spec version: 1.0
 */
import type { ModelsGenre } from "./modelsGenre";
import type { ModelsUserRole } from "./modelsUserRole";
import type { ModelsUserWatchHistory } from "./modelsUserWatchHistory";
import type { ModelsWatchProgress } from "./modelsWatchProgress";

export interface ModelsUser {
	created_at?: string;
	email: string;
	/** Engagement & Personalization */
	favorite_genres: ModelsGenre[];
	favorite_movies?: string[];
	/**
	 * @minLength 2
	 * @maxLength 100
	 */
	first_name: string;
	id?: string;
	is_email_verified?: boolean;
	is_verified_badge?: boolean;
	/**
	 * @minLength 2
	 * @maxLength 100
	 */
	last_name: string;
	/** Production Resume-Watching Feature */
	last_watched?: ModelsUserWatchHistory[];
	liked_movies?: string[];
	onboarding_done?: boolean;
	/** @minLength 6 */
	password: string;
	preferred_genres?: string[];
	refresh_token?: string;
	role: ModelsUserRole;
	/** Auth & Security */
	token?: string;
	updated_at?: string;
	user_id?: string;
	watch_history?: ModelsWatchProgress[];
	watchlist?: string[];
}
