/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Streaming App API
 * API for streaming application with WebSocket support
 * OpenAPI spec version: 1.0
 */

export interface UsersOnboardingRequest {
	/**
	 * Require at least 3
	 * @minItems 3
	 */
	genres: string[];
}
