/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Streaming App API
 * API for streaming application with WebSocket support
 * OpenAPI spec version: 1.0
 */
import type { ModelsMovie } from "./modelsMovie";
import type { ModelsWatchProgress } from "./modelsWatchProgress";

export interface UsersContinueWatchingResponse {
	movie?: ModelsMovie;
	progress?: ModelsWatchProgress;
}
