/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Streaming App API
 * API for streaming application with WebSocket support
 * OpenAPI spec version: 1.0
 */

import type {
	DataTag,
	DefinedInitialDataOptions,
	DefinedUseInfiniteQueryResult,
	DefinedUseQueryResult,
	InfiniteData,
	MutationFunction,
	QueryClient,
	QueryFunction,
	QueryKey,
	UndefinedInitialDataOptions,
	UseInfiniteQueryOptions,
	UseInfiniteQueryResult,
	UseMutationOptions,
	UseMutationResult,
	UseQueryOptions,
	UseQueryResult,
} from "@tanstack/react-query";
import { useInfiniteQuery, useMutation, useQuery } from "@tanstack/react-query";
import { customInstance } from "../../client";
import type {
	GetUserWatchlist401,
	GetUserWatchlist500,
	GithubComTeachiesStreamingApInternalDatabaseModelsMovie,
	PostUserWatchlistToggle201,
	PostUserWatchlistToggle401,
	PostUserWatchlistToggle500,
	PostUserWatchlistToggleParams,
} from "../../models";

/**
 * Returns the full movie objects for everything the user has saved.
 * @summary Get all movies in user's watchlist
 */
export const getUserWatchlist = (signal?: AbortSignal) => {
	return customInstance<
		GithubComTeachiesStreamingApInternalDatabaseModelsMovie[]
	>({ url: `/user/watchlist`, method: "GET", signal });
};

export const getGetUserWatchlistInfiniteQueryKey = () => {
	return ["infinate", `/user/watchlist`] as const;
};

export const getGetUserWatchlistQueryKey = () => {
	return [`/user/watchlist`] as const;
};

export const getGetUserWatchlistInfiniteQueryOptions = <
	TData = InfiniteData<Awaited<ReturnType<typeof getUserWatchlist>>>,
	TError = GetUserWatchlist401 | GetUserWatchlist500,
>(options?: {
	query?: Partial<
		UseInfiniteQueryOptions<
			Awaited<ReturnType<typeof getUserWatchlist>>,
			TError,
			TData
		>
	>;
}) => {
	const { query: queryOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ?? getGetUserWatchlistInfiniteQueryKey();

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof getUserWatchlist>>
	> = ({ signal }) => getUserWatchlist(signal);

	return {
		queryKey,
		queryFn,
		staleTime: 10000,
		...queryOptions,
	} as UseInfiniteQueryOptions<
		Awaited<ReturnType<typeof getUserWatchlist>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetUserWatchlistInfiniteQueryResult = NonNullable<
	Awaited<ReturnType<typeof getUserWatchlist>>
>;
export type GetUserWatchlistInfiniteQueryError =
	| GetUserWatchlist401
	| GetUserWatchlist500;

export function useGetUserWatchlistInfinite<
	TData = InfiniteData<Awaited<ReturnType<typeof getUserWatchlist>>>,
	TError = GetUserWatchlist401 | GetUserWatchlist500,
>(
	options: {
		query: Partial<
			UseInfiniteQueryOptions<
				Awaited<ReturnType<typeof getUserWatchlist>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getUserWatchlist>>,
					TError,
					Awaited<ReturnType<typeof getUserWatchlist>>
				>,
				"initialData"
			>;
	},
	queryClient?: QueryClient,
): DefinedUseInfiniteQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetUserWatchlistInfinite<
	TData = InfiniteData<Awaited<ReturnType<typeof getUserWatchlist>>>,
	TError = GetUserWatchlist401 | GetUserWatchlist500,
>(
	options?: {
		query?: Partial<
			UseInfiniteQueryOptions<
				Awaited<ReturnType<typeof getUserWatchlist>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getUserWatchlist>>,
					TError,
					Awaited<ReturnType<typeof getUserWatchlist>>
				>,
				"initialData"
			>;
	},
	queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetUserWatchlistInfinite<
	TData = InfiniteData<Awaited<ReturnType<typeof getUserWatchlist>>>,
	TError = GetUserWatchlist401 | GetUserWatchlist500,
>(
	options?: {
		query?: Partial<
			UseInfiniteQueryOptions<
				Awaited<ReturnType<typeof getUserWatchlist>>,
				TError,
				TData
			>
		>;
	},
	queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get all movies in user's watchlist
 */

export function useGetUserWatchlistInfinite<
	TData = InfiniteData<Awaited<ReturnType<typeof getUserWatchlist>>>,
	TError = GetUserWatchlist401 | GetUserWatchlist500,
>(
	options?: {
		query?: Partial<
			UseInfiniteQueryOptions<
				Awaited<ReturnType<typeof getUserWatchlist>>,
				TError,
				TData
			>
		>;
	},
	queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetUserWatchlistInfiniteQueryOptions(options);

	const query = useInfiniteQuery(
		queryOptions,
		queryClient,
	) as UseInfiniteQueryResult<TData, TError> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};

	query.queryKey = queryOptions.queryKey;

	return query;
}

export const getGetUserWatchlistQueryOptions = <
	TData = Awaited<ReturnType<typeof getUserWatchlist>>,
	TError = GetUserWatchlist401 | GetUserWatchlist500,
>(options?: {
	query?: Partial<
		UseQueryOptions<Awaited<ReturnType<typeof getUserWatchlist>>, TError, TData>
	>;
}) => {
	const { query: queryOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getGetUserWatchlistQueryKey();

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof getUserWatchlist>>
	> = ({ signal }) => getUserWatchlist(signal);

	return {
		queryKey,
		queryFn,
		staleTime: 10000,
		...queryOptions,
	} as UseQueryOptions<
		Awaited<ReturnType<typeof getUserWatchlist>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetUserWatchlistQueryResult = NonNullable<
	Awaited<ReturnType<typeof getUserWatchlist>>
>;
export type GetUserWatchlistQueryError =
	| GetUserWatchlist401
	| GetUserWatchlist500;

export function useGetUserWatchlist<
	TData = Awaited<ReturnType<typeof getUserWatchlist>>,
	TError = GetUserWatchlist401 | GetUserWatchlist500,
>(
	options: {
		query: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getUserWatchlist>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getUserWatchlist>>,
					TError,
					Awaited<ReturnType<typeof getUserWatchlist>>
				>,
				"initialData"
			>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetUserWatchlist<
	TData = Awaited<ReturnType<typeof getUserWatchlist>>,
	TError = GetUserWatchlist401 | GetUserWatchlist500,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getUserWatchlist>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getUserWatchlist>>,
					TError,
					Awaited<ReturnType<typeof getUserWatchlist>>
				>,
				"initialData"
			>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetUserWatchlist<
	TData = Awaited<ReturnType<typeof getUserWatchlist>>,
	TError = GetUserWatchlist401 | GetUserWatchlist500,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getUserWatchlist>>,
				TError,
				TData
			>
		>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get all movies in user's watchlist
 */

export function useGetUserWatchlist<
	TData = Awaited<ReturnType<typeof getUserWatchlist>>,
	TError = GetUserWatchlist401 | GetUserWatchlist500,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getUserWatchlist>>,
				TError,
				TData
			>
		>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetUserWatchlistQueryOptions(options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	query.queryKey = queryOptions.queryKey;

	return query;
}

/**
 * Toggles a movie in the user's watchlist. Returns 'added: true' if added, 'added: false' if removed.
 * @summary Add or Remove movie from watchlist
 */
export const postUserWatchlistToggle = (
	params: PostUserWatchlistToggleParams,
	signal?: AbortSignal,
) => {
	return customInstance<PostUserWatchlistToggle201>({
		url: `/user/watchlist/toggle`,
		method: "POST",
		params,
		signal,
	});
};

export const getPostUserWatchlistToggleMutationOptions = <
	TError = PostUserWatchlistToggle401 | PostUserWatchlistToggle500,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof postUserWatchlistToggle>>,
		TError,
		{ params: PostUserWatchlistToggleParams },
		TContext
	>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof postUserWatchlistToggle>>,
	TError,
	{ params: PostUserWatchlistToggleParams },
	TContext
> => {
	const mutationKey = ["postUserWatchlistToggle"];
	const { mutation: mutationOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey } };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof postUserWatchlistToggle>>,
		{ params: PostUserWatchlistToggleParams }
	> = (props) => {
		const { params } = props ?? {};

		return postUserWatchlistToggle(params);
	};

	return { mutationFn, ...mutationOptions };
};

export type PostUserWatchlistToggleMutationResult = NonNullable<
	Awaited<ReturnType<typeof postUserWatchlistToggle>>
>;

export type PostUserWatchlistToggleMutationError =
	| PostUserWatchlistToggle401
	| PostUserWatchlistToggle500;

/**
 * @summary Add or Remove movie from watchlist
 */
export const usePostUserWatchlistToggle = <
	TError = PostUserWatchlistToggle401 | PostUserWatchlistToggle500,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof postUserWatchlistToggle>>,
			TError,
			{ params: PostUserWatchlistToggleParams },
			TContext
		>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof postUserWatchlistToggle>>,
	TError,
	{ params: PostUserWatchlistToggleParams },
	TContext
> => {
	const mutationOptions = getPostUserWatchlistToggleMutationOptions(options);

	return useMutation(mutationOptions, queryClient);
};
