/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Streaming App API
 * API for streaming application with WebSocket support
 * OpenAPI spec version: 1.0
 */

import type {
	MutationFunction,
	QueryClient,
	UseMutationOptions,
	UseMutationResult,
} from "@tanstack/react-query";
import { useMutation } from "@tanstack/react-query";
import { customInstance } from "../../client";
import type {
	GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse,
	GithubComTeachiesStreamingApInternalDatabaseModelsApiSuccessResponse,
} from "../../models";

/**
 * Adds movie to user's liked list and increments global movie likes.
 * @summary Like a movie
 */
export const postUsersMeLikeImdbId = (imdbId: string, signal?: AbortSignal) => {
	return customInstance<GithubComTeachiesStreamingApInternalDatabaseModelsApiSuccessResponse>(
		{ url: `/users/me/like/${imdbId}`, method: "POST", signal },
	);
};

export const getPostUsersMeLikeImdbIdMutationOptions = <
	TError = unknown,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof postUsersMeLikeImdbId>>,
		TError,
		{ imdbId: string },
		TContext
	>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof postUsersMeLikeImdbId>>,
	TError,
	{ imdbId: string },
	TContext
> => {
	const mutationKey = ["postUsersMeLikeImdbId"];
	const { mutation: mutationOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey } };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof postUsersMeLikeImdbId>>,
		{ imdbId: string }
	> = (props) => {
		const { imdbId } = props ?? {};

		return postUsersMeLikeImdbId(imdbId);
	};

	return { mutationFn, ...mutationOptions };
};

export type PostUsersMeLikeImdbIdMutationResult = NonNullable<
	Awaited<ReturnType<typeof postUsersMeLikeImdbId>>
>;

export type PostUsersMeLikeImdbIdMutationError = unknown;

/**
 * @summary Like a movie
 */
export const usePostUsersMeLikeImdbId = <TError = unknown, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof postUsersMeLikeImdbId>>,
			TError,
			{ imdbId: string },
			TContext
		>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof postUsersMeLikeImdbId>>,
	TError,
	{ imdbId: string },
	TContext
> => {
	const mutationOptions = getPostUsersMeLikeImdbIdMutationOptions(options);

	return useMutation(mutationOptions, queryClient);
};
/**
 * Removes movie from user's liked list and decrements global movie likes.
 * @summary Unlike a movie
 */
export const deleteUsersMeUnlikeImdbId = (imdbId: string) => {
	return customInstance<GithubComTeachiesStreamingApInternalDatabaseModelsApiSuccessResponse>(
		{ url: `/users/me/unlike/${imdbId}`, method: "DELETE" },
	);
};

export const getDeleteUsersMeUnlikeImdbIdMutationOptions = <
	TError =
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof deleteUsersMeUnlikeImdbId>>,
		TError,
		{ imdbId: string },
		TContext
	>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof deleteUsersMeUnlikeImdbId>>,
	TError,
	{ imdbId: string },
	TContext
> => {
	const mutationKey = ["deleteUsersMeUnlikeImdbId"];
	const { mutation: mutationOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey } };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof deleteUsersMeUnlikeImdbId>>,
		{ imdbId: string }
	> = (props) => {
		const { imdbId } = props ?? {};

		return deleteUsersMeUnlikeImdbId(imdbId);
	};

	return { mutationFn, ...mutationOptions };
};

export type DeleteUsersMeUnlikeImdbIdMutationResult = NonNullable<
	Awaited<ReturnType<typeof deleteUsersMeUnlikeImdbId>>
>;

export type DeleteUsersMeUnlikeImdbIdMutationError =
	| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse
	| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse;

/**
 * @summary Unlike a movie
 */
export const useDeleteUsersMeUnlikeImdbId = <
	TError =
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof deleteUsersMeUnlikeImdbId>>,
			TError,
			{ imdbId: string },
			TContext
		>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof deleteUsersMeUnlikeImdbId>>,
	TError,
	{ imdbId: string },
	TContext
> => {
	const mutationOptions = getDeleteUsersMeUnlikeImdbIdMutationOptions(options);

	return useMutation(mutationOptions, queryClient);
};
