/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Streaming App API
 * API for streaming application with WebSocket support
 * OpenAPI spec version: 1.0
 */

import type {
	DataTag,
	DefinedInitialDataOptions,
	DefinedUseInfiniteQueryResult,
	DefinedUseQueryResult,
	InfiniteData,
	MutationFunction,
	QueryClient,
	QueryFunction,
	QueryKey,
	UndefinedInitialDataOptions,
	UseInfiniteQueryOptions,
	UseInfiniteQueryResult,
	UseMutationOptions,
	UseMutationResult,
	UseQueryOptions,
	UseQueryResult,
} from "@tanstack/react-query";
import { useInfiniteQuery, useMutation, useQuery } from "@tanstack/react-query";
import { customInstance } from "../../client";
import type {
	DeleteUserHistoryClear200,
	DeleteUserHistoryClear500,
	DeleteUserHistoryImdbId200,
	DeleteUserHistoryImdbId400,
	DeleteUserHistoryImdbId500,
	GetUserHistoryContinue401,
	GetUserHistoryContinue500,
	InternalApiControllersUsersContinueWatchingResponse,
} from "../../models";

/**
 * @summary Clear all watch history
 */
export const deleteUserHistoryClear = () => {
	return customInstance<DeleteUserHistoryClear200>({
		url: `/user/history/clear`,
		method: "DELETE",
	});
};

export const getDeleteUserHistoryClearMutationOptions = <
	TError = DeleteUserHistoryClear500,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof deleteUserHistoryClear>>,
		TError,
		void,
		TContext
	>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof deleteUserHistoryClear>>,
	TError,
	void,
	TContext
> => {
	const mutationKey = ["deleteUserHistoryClear"];
	const { mutation: mutationOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey } };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof deleteUserHistoryClear>>,
		void
	> = () => {
		return deleteUserHistoryClear();
	};

	return { mutationFn, ...mutationOptions };
};

export type DeleteUserHistoryClearMutationResult = NonNullable<
	Awaited<ReturnType<typeof deleteUserHistoryClear>>
>;

export type DeleteUserHistoryClearMutationError = DeleteUserHistoryClear500;

/**
 * @summary Clear all watch history
 */
export const useDeleteUserHistoryClear = <
	TError = DeleteUserHistoryClear500,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof deleteUserHistoryClear>>,
			TError,
			void,
			TContext
		>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof deleteUserHistoryClear>>,
	TError,
	void,
	TContext
> => {
	const mutationOptions = getDeleteUserHistoryClearMutationOptions(options);

	return useMutation(mutationOptions, queryClient);
};
/**
 * Retrieves a list of movies the user has started watching, sorted by most recent activity. Includes movie metadata for rendering.
 * @summary Get user's recent watch history
 */
export const getUserHistoryContinue = (signal?: AbortSignal) => {
	return customInstance<InternalApiControllersUsersContinueWatchingResponse[]>({
		url: `/user/history/continue`,
		method: "GET",
		signal,
	});
};

export const getGetUserHistoryContinueInfiniteQueryKey = () => {
	return ["infinate", `/user/history/continue`] as const;
};

export const getGetUserHistoryContinueQueryKey = () => {
	return [`/user/history/continue`] as const;
};

export const getGetUserHistoryContinueInfiniteQueryOptions = <
	TData = InfiniteData<Awaited<ReturnType<typeof getUserHistoryContinue>>>,
	TError = GetUserHistoryContinue401 | GetUserHistoryContinue500,
>(options?: {
	query?: Partial<
		UseInfiniteQueryOptions<
			Awaited<ReturnType<typeof getUserHistoryContinue>>,
			TError,
			TData
		>
	>;
}) => {
	const { query: queryOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ?? getGetUserHistoryContinueInfiniteQueryKey();

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof getUserHistoryContinue>>
	> = ({ signal }) => getUserHistoryContinue(signal);

	return {
		queryKey,
		queryFn,
		staleTime: 10000,
		...queryOptions,
	} as UseInfiniteQueryOptions<
		Awaited<ReturnType<typeof getUserHistoryContinue>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetUserHistoryContinueInfiniteQueryResult = NonNullable<
	Awaited<ReturnType<typeof getUserHistoryContinue>>
>;
export type GetUserHistoryContinueInfiniteQueryError =
	| GetUserHistoryContinue401
	| GetUserHistoryContinue500;

export function useGetUserHistoryContinueInfinite<
	TData = InfiniteData<Awaited<ReturnType<typeof getUserHistoryContinue>>>,
	TError = GetUserHistoryContinue401 | GetUserHistoryContinue500,
>(
	options: {
		query: Partial<
			UseInfiniteQueryOptions<
				Awaited<ReturnType<typeof getUserHistoryContinue>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getUserHistoryContinue>>,
					TError,
					Awaited<ReturnType<typeof getUserHistoryContinue>>
				>,
				"initialData"
			>;
	},
	queryClient?: QueryClient,
): DefinedUseInfiniteQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetUserHistoryContinueInfinite<
	TData = InfiniteData<Awaited<ReturnType<typeof getUserHistoryContinue>>>,
	TError = GetUserHistoryContinue401 | GetUserHistoryContinue500,
>(
	options?: {
		query?: Partial<
			UseInfiniteQueryOptions<
				Awaited<ReturnType<typeof getUserHistoryContinue>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getUserHistoryContinue>>,
					TError,
					Awaited<ReturnType<typeof getUserHistoryContinue>>
				>,
				"initialData"
			>;
	},
	queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetUserHistoryContinueInfinite<
	TData = InfiniteData<Awaited<ReturnType<typeof getUserHistoryContinue>>>,
	TError = GetUserHistoryContinue401 | GetUserHistoryContinue500,
>(
	options?: {
		query?: Partial<
			UseInfiniteQueryOptions<
				Awaited<ReturnType<typeof getUserHistoryContinue>>,
				TError,
				TData
			>
		>;
	},
	queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get user's recent watch history
 */

export function useGetUserHistoryContinueInfinite<
	TData = InfiniteData<Awaited<ReturnType<typeof getUserHistoryContinue>>>,
	TError = GetUserHistoryContinue401 | GetUserHistoryContinue500,
>(
	options?: {
		query?: Partial<
			UseInfiniteQueryOptions<
				Awaited<ReturnType<typeof getUserHistoryContinue>>,
				TError,
				TData
			>
		>;
	},
	queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetUserHistoryContinueInfiniteQueryOptions(options);

	const query = useInfiniteQuery(
		queryOptions,
		queryClient,
	) as UseInfiniteQueryResult<TData, TError> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};

	query.queryKey = queryOptions.queryKey;

	return query;
}

export const getGetUserHistoryContinueQueryOptions = <
	TData = Awaited<ReturnType<typeof getUserHistoryContinue>>,
	TError = GetUserHistoryContinue401 | GetUserHistoryContinue500,
>(options?: {
	query?: Partial<
		UseQueryOptions<
			Awaited<ReturnType<typeof getUserHistoryContinue>>,
			TError,
			TData
		>
	>;
}) => {
	const { query: queryOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ?? getGetUserHistoryContinueQueryKey();

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof getUserHistoryContinue>>
	> = ({ signal }) => getUserHistoryContinue(signal);

	return {
		queryKey,
		queryFn,
		staleTime: 10000,
		...queryOptions,
	} as UseQueryOptions<
		Awaited<ReturnType<typeof getUserHistoryContinue>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetUserHistoryContinueQueryResult = NonNullable<
	Awaited<ReturnType<typeof getUserHistoryContinue>>
>;
export type GetUserHistoryContinueQueryError =
	| GetUserHistoryContinue401
	| GetUserHistoryContinue500;

export function useGetUserHistoryContinue<
	TData = Awaited<ReturnType<typeof getUserHistoryContinue>>,
	TError = GetUserHistoryContinue401 | GetUserHistoryContinue500,
>(
	options: {
		query: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getUserHistoryContinue>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getUserHistoryContinue>>,
					TError,
					Awaited<ReturnType<typeof getUserHistoryContinue>>
				>,
				"initialData"
			>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetUserHistoryContinue<
	TData = Awaited<ReturnType<typeof getUserHistoryContinue>>,
	TError = GetUserHistoryContinue401 | GetUserHistoryContinue500,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getUserHistoryContinue>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getUserHistoryContinue>>,
					TError,
					Awaited<ReturnType<typeof getUserHistoryContinue>>
				>,
				"initialData"
			>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetUserHistoryContinue<
	TData = Awaited<ReturnType<typeof getUserHistoryContinue>>,
	TError = GetUserHistoryContinue401 | GetUserHistoryContinue500,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getUserHistoryContinue>>,
				TError,
				TData
			>
		>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get user's recent watch history
 */

export function useGetUserHistoryContinue<
	TData = Awaited<ReturnType<typeof getUserHistoryContinue>>,
	TError = GetUserHistoryContinue401 | GetUserHistoryContinue500,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getUserHistoryContinue>>,
				TError,
				TData
			>
		>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetUserHistoryContinueQueryOptions(options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	query.queryKey = queryOptions.queryKey;

	return query;
}

/**
 * Removes one single entry from the user's history array.
 * @summary Remove a specific movie from watch history
 */
export const deleteUserHistoryImdbId = (imdbId: string) => {
	return customInstance<DeleteUserHistoryImdbId200>({
		url: `/user/history/${imdbId}`,
		method: "DELETE",
	});
};

export const getDeleteUserHistoryImdbIdMutationOptions = <
	TError = DeleteUserHistoryImdbId400 | DeleteUserHistoryImdbId500,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof deleteUserHistoryImdbId>>,
		TError,
		{ imdbId: string },
		TContext
	>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof deleteUserHistoryImdbId>>,
	TError,
	{ imdbId: string },
	TContext
> => {
	const mutationKey = ["deleteUserHistoryImdbId"];
	const { mutation: mutationOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey } };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof deleteUserHistoryImdbId>>,
		{ imdbId: string }
	> = (props) => {
		const { imdbId } = props ?? {};

		return deleteUserHistoryImdbId(imdbId);
	};

	return { mutationFn, ...mutationOptions };
};

export type DeleteUserHistoryImdbIdMutationResult = NonNullable<
	Awaited<ReturnType<typeof deleteUserHistoryImdbId>>
>;

export type DeleteUserHistoryImdbIdMutationError =
	| DeleteUserHistoryImdbId400
	| DeleteUserHistoryImdbId500;

/**
 * @summary Remove a specific movie from watch history
 */
export const useDeleteUserHistoryImdbId = <
	TError = DeleteUserHistoryImdbId400 | DeleteUserHistoryImdbId500,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof deleteUserHistoryImdbId>>,
			TError,
			{ imdbId: string },
			TContext
		>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof deleteUserHistoryImdbId>>,
	TError,
	{ imdbId: string },
	TContext
> => {
	const mutationOptions = getDeleteUserHistoryImdbIdMutationOptions(options);

	return useMutation(mutationOptions, queryClient);
};
