/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Streaming App API
 * API for streaming application with WebSocket support
 * OpenAPI spec version: 1.0
 */

import type {
	DataTag,
	DefinedInitialDataOptions,
	DefinedUseInfiniteQueryResult,
	DefinedUseQueryResult,
	InfiniteData,
	MutationFunction,
	QueryClient,
	QueryFunction,
	QueryKey,
	UndefinedInitialDataOptions,
	UseInfiniteQueryOptions,
	UseInfiniteQueryResult,
	UseMutationOptions,
	UseMutationResult,
	UseQueryOptions,
	UseQueryResult,
} from "@tanstack/react-query";
import { useInfiniteQuery, useMutation, useQuery } from "@tanstack/react-query";
import { customInstance } from "../../client";
import type {
	GetMoviesParams,
	GetMoviesSearchParams,
	GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse,
	GithubComTeachiesStreamingApInternalDatabaseModelsApiSuccessResponse,
	GithubComTeachiesStreamingApInternalDatabaseModelsMovie,
	GithubComTeachiesStreamingApInternalDatabaseModelsUpdateMovieRequest,
	PatchMoviesImdbIdReviewBody,
} from "../../models";

/**
 * Advanced filtering for movies with pagination support using standardized API responses.
 * @summary Search and Filter movies
 */
export const getMovies = (params?: GetMoviesParams, signal?: AbortSignal) => {
	return customInstance<GithubComTeachiesStreamingApInternalDatabaseModelsApiSuccessResponse>(
		{ url: `/movies`, method: "GET", params, signal },
	);
};

export const getGetMoviesInfiniteQueryKey = (params?: GetMoviesParams) => {
	return ["infinate", `/movies`, ...(params ? [params] : [])] as const;
};

export const getGetMoviesQueryKey = (params?: GetMoviesParams) => {
	return [`/movies`, ...(params ? [params] : [])] as const;
};

export const getGetMoviesInfiniteQueryOptions = <
	TData = InfiniteData<
		Awaited<ReturnType<typeof getMovies>>,
		GetMoviesParams["page"]
	>,
	TError =
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse,
>(
	params?: GetMoviesParams,
	options?: {
		query?: Partial<
			UseInfiniteQueryOptions<
				Awaited<ReturnType<typeof getMovies>>,
				TError,
				TData,
				Awaited<ReturnType<typeof getMovies>>,
				QueryKey,
				GetMoviesParams["page"]
			>
		>;
	},
) => {
	const { query: queryOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ?? getGetMoviesInfiniteQueryKey(params);

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof getMovies>>,
		QueryKey,
		GetMoviesParams["page"]
	> = ({ signal, pageParam }) =>
		getMovies({ ...params, page: pageParam || params?.page }, signal);

	return {
		queryKey,
		queryFn,
		staleTime: 10000,
		...queryOptions,
	} as UseInfiniteQueryOptions<
		Awaited<ReturnType<typeof getMovies>>,
		TError,
		TData,
		Awaited<ReturnType<typeof getMovies>>,
		QueryKey,
		GetMoviesParams["page"]
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetMoviesInfiniteQueryResult = NonNullable<
	Awaited<ReturnType<typeof getMovies>>
>;
export type GetMoviesInfiniteQueryError =
	| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse
	| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse;

export function useGetMoviesInfinite<
	TData = InfiniteData<
		Awaited<ReturnType<typeof getMovies>>,
		GetMoviesParams["page"]
	>,
	TError =
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse,
>(
	params: undefined | GetMoviesParams,
	options: {
		query: Partial<
			UseInfiniteQueryOptions<
				Awaited<ReturnType<typeof getMovies>>,
				TError,
				TData,
				Awaited<ReturnType<typeof getMovies>>,
				QueryKey,
				GetMoviesParams["page"]
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getMovies>>,
					TError,
					Awaited<ReturnType<typeof getMovies>>,
					QueryKey
				>,
				"initialData"
			>;
	},
	queryClient?: QueryClient,
): DefinedUseInfiniteQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetMoviesInfinite<
	TData = InfiniteData<
		Awaited<ReturnType<typeof getMovies>>,
		GetMoviesParams["page"]
	>,
	TError =
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse,
>(
	params?: GetMoviesParams,
	options?: {
		query?: Partial<
			UseInfiniteQueryOptions<
				Awaited<ReturnType<typeof getMovies>>,
				TError,
				TData,
				Awaited<ReturnType<typeof getMovies>>,
				QueryKey,
				GetMoviesParams["page"]
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getMovies>>,
					TError,
					Awaited<ReturnType<typeof getMovies>>,
					QueryKey
				>,
				"initialData"
			>;
	},
	queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetMoviesInfinite<
	TData = InfiniteData<
		Awaited<ReturnType<typeof getMovies>>,
		GetMoviesParams["page"]
	>,
	TError =
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse,
>(
	params?: GetMoviesParams,
	options?: {
		query?: Partial<
			UseInfiniteQueryOptions<
				Awaited<ReturnType<typeof getMovies>>,
				TError,
				TData,
				Awaited<ReturnType<typeof getMovies>>,
				QueryKey,
				GetMoviesParams["page"]
			>
		>;
	},
	queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Search and Filter movies
 */

export function useGetMoviesInfinite<
	TData = InfiniteData<
		Awaited<ReturnType<typeof getMovies>>,
		GetMoviesParams["page"]
	>,
	TError =
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse,
>(
	params?: GetMoviesParams,
	options?: {
		query?: Partial<
			UseInfiniteQueryOptions<
				Awaited<ReturnType<typeof getMovies>>,
				TError,
				TData,
				Awaited<ReturnType<typeof getMovies>>,
				QueryKey,
				GetMoviesParams["page"]
			>
		>;
	},
	queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetMoviesInfiniteQueryOptions(params, options);

	const query = useInfiniteQuery(
		queryOptions,
		queryClient,
	) as UseInfiniteQueryResult<TData, TError> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};

	query.queryKey = queryOptions.queryKey;

	return query;
}

export const getGetMoviesQueryOptions = <
	TData = Awaited<ReturnType<typeof getMovies>>,
	TError =
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse,
>(
	params?: GetMoviesParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getMovies>>, TError, TData>
		>;
	},
) => {
	const { query: queryOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getGetMoviesQueryKey(params);

	const queryFn: QueryFunction<Awaited<ReturnType<typeof getMovies>>> = ({
		signal,
	}) => getMovies(params, signal);

	return {
		queryKey,
		queryFn,
		staleTime: 10000,
		...queryOptions,
	} as UseQueryOptions<Awaited<ReturnType<typeof getMovies>>, TError, TData> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};
};

export type GetMoviesQueryResult = NonNullable<
	Awaited<ReturnType<typeof getMovies>>
>;
export type GetMoviesQueryError =
	| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse
	| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse;

export function useGetMovies<
	TData = Awaited<ReturnType<typeof getMovies>>,
	TError =
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse,
>(
	params: undefined | GetMoviesParams,
	options: {
		query: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getMovies>>, TError, TData>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getMovies>>,
					TError,
					Awaited<ReturnType<typeof getMovies>>
				>,
				"initialData"
			>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetMovies<
	TData = Awaited<ReturnType<typeof getMovies>>,
	TError =
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse,
>(
	params?: GetMoviesParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getMovies>>, TError, TData>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getMovies>>,
					TError,
					Awaited<ReturnType<typeof getMovies>>
				>,
				"initialData"
			>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetMovies<
	TData = Awaited<ReturnType<typeof getMovies>>,
	TError =
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse,
>(
	params?: GetMoviesParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getMovies>>, TError, TData>
		>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Search and Filter movies
 */

export function useGetMovies<
	TData = Awaited<ReturnType<typeof getMovies>>,
	TError =
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse,
>(
	params?: GetMoviesParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getMovies>>, TError, TData>
		>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetMoviesQueryOptions(params, options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	query.queryKey = queryOptions.queryKey;

	return query;
}

/**
 * Add a new movie document to the collection and index it in Elasticsearch.
 * @summary Create a new movie
 */
export const postMovies = (
	githubComTeachiesStreamingApInternalDatabaseModelsMovie: GithubComTeachiesStreamingApInternalDatabaseModelsMovie,
	signal?: AbortSignal,
) => {
	return customInstance<GithubComTeachiesStreamingApInternalDatabaseModelsApiSuccessResponse>(
		{
			url: `/movies`,
			method: "POST",
			headers: { "Content-Type": "application/json" },
			data: githubComTeachiesStreamingApInternalDatabaseModelsMovie,
			signal,
		},
	);
};

export const getPostMoviesMutationOptions = <
	TError =
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof postMovies>>,
		TError,
		{ data: GithubComTeachiesStreamingApInternalDatabaseModelsMovie },
		TContext
	>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof postMovies>>,
	TError,
	{ data: GithubComTeachiesStreamingApInternalDatabaseModelsMovie },
	TContext
> => {
	const mutationKey = ["postMovies"];
	const { mutation: mutationOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey } };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof postMovies>>,
		{ data: GithubComTeachiesStreamingApInternalDatabaseModelsMovie }
	> = (props) => {
		const { data } = props ?? {};

		return postMovies(data);
	};

	return { mutationFn, ...mutationOptions };
};

export type PostMoviesMutationResult = NonNullable<
	Awaited<ReturnType<typeof postMovies>>
>;
export type PostMoviesMutationBody =
	GithubComTeachiesStreamingApInternalDatabaseModelsMovie;
export type PostMoviesMutationError =
	| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse
	| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse;

/**
 * @summary Create a new movie
 */
export const usePostMovies = <
	TError =
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof postMovies>>,
			TError,
			{ data: GithubComTeachiesStreamingApInternalDatabaseModelsMovie },
			TContext
		>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof postMovies>>,
	TError,
	{ data: GithubComTeachiesStreamingApInternalDatabaseModelsMovie },
	TContext
> => {
	const mutationOptions = getPostMoviesMutationOptions(options);

	return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Get personalized movie recommendations
 */
export const getMoviesRecommended = (signal?: AbortSignal) => {
	return customInstance<
		GithubComTeachiesStreamingApInternalDatabaseModelsMovie[]
	>({ url: `/movies/recommended`, method: "GET", signal });
};

export const getGetMoviesRecommendedInfiniteQueryKey = () => {
	return ["infinate", `/movies/recommended`] as const;
};

export const getGetMoviesRecommendedQueryKey = () => {
	return [`/movies/recommended`] as const;
};

export const getGetMoviesRecommendedInfiniteQueryOptions = <
	TData = InfiniteData<Awaited<ReturnType<typeof getMoviesRecommended>>>,
	TError = unknown,
>(options?: {
	query?: Partial<
		UseInfiniteQueryOptions<
			Awaited<ReturnType<typeof getMoviesRecommended>>,
			TError,
			TData
		>
	>;
}) => {
	const { query: queryOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ?? getGetMoviesRecommendedInfiniteQueryKey();

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof getMoviesRecommended>>
	> = ({ signal }) => getMoviesRecommended(signal);

	return {
		queryKey,
		queryFn,
		staleTime: 10000,
		...queryOptions,
	} as UseInfiniteQueryOptions<
		Awaited<ReturnType<typeof getMoviesRecommended>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetMoviesRecommendedInfiniteQueryResult = NonNullable<
	Awaited<ReturnType<typeof getMoviesRecommended>>
>;
export type GetMoviesRecommendedInfiniteQueryError = unknown;

export function useGetMoviesRecommendedInfinite<
	TData = InfiniteData<Awaited<ReturnType<typeof getMoviesRecommended>>>,
	TError = unknown,
>(
	options: {
		query: Partial<
			UseInfiniteQueryOptions<
				Awaited<ReturnType<typeof getMoviesRecommended>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getMoviesRecommended>>,
					TError,
					Awaited<ReturnType<typeof getMoviesRecommended>>
				>,
				"initialData"
			>;
	},
	queryClient?: QueryClient,
): DefinedUseInfiniteQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetMoviesRecommendedInfinite<
	TData = InfiniteData<Awaited<ReturnType<typeof getMoviesRecommended>>>,
	TError = unknown,
>(
	options?: {
		query?: Partial<
			UseInfiniteQueryOptions<
				Awaited<ReturnType<typeof getMoviesRecommended>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getMoviesRecommended>>,
					TError,
					Awaited<ReturnType<typeof getMoviesRecommended>>
				>,
				"initialData"
			>;
	},
	queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetMoviesRecommendedInfinite<
	TData = InfiniteData<Awaited<ReturnType<typeof getMoviesRecommended>>>,
	TError = unknown,
>(
	options?: {
		query?: Partial<
			UseInfiniteQueryOptions<
				Awaited<ReturnType<typeof getMoviesRecommended>>,
				TError,
				TData
			>
		>;
	},
	queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get personalized movie recommendations
 */

export function useGetMoviesRecommendedInfinite<
	TData = InfiniteData<Awaited<ReturnType<typeof getMoviesRecommended>>>,
	TError = unknown,
>(
	options?: {
		query?: Partial<
			UseInfiniteQueryOptions<
				Awaited<ReturnType<typeof getMoviesRecommended>>,
				TError,
				TData
			>
		>;
	},
	queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetMoviesRecommendedInfiniteQueryOptions(options);

	const query = useInfiniteQuery(
		queryOptions,
		queryClient,
	) as UseInfiniteQueryResult<TData, TError> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};

	query.queryKey = queryOptions.queryKey;

	return query;
}

export const getGetMoviesRecommendedQueryOptions = <
	TData = Awaited<ReturnType<typeof getMoviesRecommended>>,
	TError = unknown,
>(options?: {
	query?: Partial<
		UseQueryOptions<
			Awaited<ReturnType<typeof getMoviesRecommended>>,
			TError,
			TData
		>
	>;
}) => {
	const { query: queryOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getGetMoviesRecommendedQueryKey();

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof getMoviesRecommended>>
	> = ({ signal }) => getMoviesRecommended(signal);

	return {
		queryKey,
		queryFn,
		staleTime: 10000,
		...queryOptions,
	} as UseQueryOptions<
		Awaited<ReturnType<typeof getMoviesRecommended>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetMoviesRecommendedQueryResult = NonNullable<
	Awaited<ReturnType<typeof getMoviesRecommended>>
>;
export type GetMoviesRecommendedQueryError = unknown;

export function useGetMoviesRecommended<
	TData = Awaited<ReturnType<typeof getMoviesRecommended>>,
	TError = unknown,
>(
	options: {
		query: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getMoviesRecommended>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getMoviesRecommended>>,
					TError,
					Awaited<ReturnType<typeof getMoviesRecommended>>
				>,
				"initialData"
			>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetMoviesRecommended<
	TData = Awaited<ReturnType<typeof getMoviesRecommended>>,
	TError = unknown,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getMoviesRecommended>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getMoviesRecommended>>,
					TError,
					Awaited<ReturnType<typeof getMoviesRecommended>>
				>,
				"initialData"
			>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetMoviesRecommended<
	TData = Awaited<ReturnType<typeof getMoviesRecommended>>,
	TError = unknown,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getMoviesRecommended>>,
				TError,
				TData
			>
		>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get personalized movie recommendations
 */

export function useGetMoviesRecommended<
	TData = Awaited<ReturnType<typeof getMoviesRecommended>>,
	TError = unknown,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getMoviesRecommended>>,
				TError,
				TData
			>
		>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetMoviesRecommendedQueryOptions(options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	query.queryKey = queryOptions.queryKey;

	return query;
}

/**
 * Advanced fuzzy search with filtering by genre, ranking, and pagination.
 * @summary Search movies via Elasticsearch
 */
export const getMoviesSearch = (
	params: GetMoviesSearchParams,
	signal?: AbortSignal,
) => {
	return customInstance<GithubComTeachiesStreamingApInternalDatabaseModelsApiSuccessResponse>(
		{ url: `/movies/search`, method: "GET", params, signal },
	);
};

export const getGetMoviesSearchInfiniteQueryKey = (
	params?: GetMoviesSearchParams,
) => {
	return ["infinate", `/movies/search`, ...(params ? [params] : [])] as const;
};

export const getGetMoviesSearchQueryKey = (params?: GetMoviesSearchParams) => {
	return [`/movies/search`, ...(params ? [params] : [])] as const;
};

export const getGetMoviesSearchInfiniteQueryOptions = <
	TData = InfiniteData<
		Awaited<ReturnType<typeof getMoviesSearch>>,
		GetMoviesSearchParams["page"]
	>,
	TError =
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse,
>(
	params: GetMoviesSearchParams,
	options?: {
		query?: Partial<
			UseInfiniteQueryOptions<
				Awaited<ReturnType<typeof getMoviesSearch>>,
				TError,
				TData,
				Awaited<ReturnType<typeof getMoviesSearch>>,
				QueryKey,
				GetMoviesSearchParams["page"]
			>
		>;
	},
) => {
	const { query: queryOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ?? getGetMoviesSearchInfiniteQueryKey(params);

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof getMoviesSearch>>,
		QueryKey,
		GetMoviesSearchParams["page"]
	> = ({ signal, pageParam }) =>
		getMoviesSearch({ ...params, page: pageParam || params?.page }, signal);

	return {
		queryKey,
		queryFn,
		staleTime: 10000,
		...queryOptions,
	} as UseInfiniteQueryOptions<
		Awaited<ReturnType<typeof getMoviesSearch>>,
		TError,
		TData,
		Awaited<ReturnType<typeof getMoviesSearch>>,
		QueryKey,
		GetMoviesSearchParams["page"]
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetMoviesSearchInfiniteQueryResult = NonNullable<
	Awaited<ReturnType<typeof getMoviesSearch>>
>;
export type GetMoviesSearchInfiniteQueryError =
	| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse
	| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse;

export function useGetMoviesSearchInfinite<
	TData = InfiniteData<
		Awaited<ReturnType<typeof getMoviesSearch>>,
		GetMoviesSearchParams["page"]
	>,
	TError =
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse,
>(
	params: GetMoviesSearchParams,
	options: {
		query: Partial<
			UseInfiniteQueryOptions<
				Awaited<ReturnType<typeof getMoviesSearch>>,
				TError,
				TData,
				Awaited<ReturnType<typeof getMoviesSearch>>,
				QueryKey,
				GetMoviesSearchParams["page"]
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getMoviesSearch>>,
					TError,
					Awaited<ReturnType<typeof getMoviesSearch>>,
					QueryKey
				>,
				"initialData"
			>;
	},
	queryClient?: QueryClient,
): DefinedUseInfiniteQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetMoviesSearchInfinite<
	TData = InfiniteData<
		Awaited<ReturnType<typeof getMoviesSearch>>,
		GetMoviesSearchParams["page"]
	>,
	TError =
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse,
>(
	params: GetMoviesSearchParams,
	options?: {
		query?: Partial<
			UseInfiniteQueryOptions<
				Awaited<ReturnType<typeof getMoviesSearch>>,
				TError,
				TData,
				Awaited<ReturnType<typeof getMoviesSearch>>,
				QueryKey,
				GetMoviesSearchParams["page"]
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getMoviesSearch>>,
					TError,
					Awaited<ReturnType<typeof getMoviesSearch>>,
					QueryKey
				>,
				"initialData"
			>;
	},
	queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetMoviesSearchInfinite<
	TData = InfiniteData<
		Awaited<ReturnType<typeof getMoviesSearch>>,
		GetMoviesSearchParams["page"]
	>,
	TError =
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse,
>(
	params: GetMoviesSearchParams,
	options?: {
		query?: Partial<
			UseInfiniteQueryOptions<
				Awaited<ReturnType<typeof getMoviesSearch>>,
				TError,
				TData,
				Awaited<ReturnType<typeof getMoviesSearch>>,
				QueryKey,
				GetMoviesSearchParams["page"]
			>
		>;
	},
	queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Search movies via Elasticsearch
 */

export function useGetMoviesSearchInfinite<
	TData = InfiniteData<
		Awaited<ReturnType<typeof getMoviesSearch>>,
		GetMoviesSearchParams["page"]
	>,
	TError =
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse,
>(
	params: GetMoviesSearchParams,
	options?: {
		query?: Partial<
			UseInfiniteQueryOptions<
				Awaited<ReturnType<typeof getMoviesSearch>>,
				TError,
				TData,
				Awaited<ReturnType<typeof getMoviesSearch>>,
				QueryKey,
				GetMoviesSearchParams["page"]
			>
		>;
	},
	queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetMoviesSearchInfiniteQueryOptions(params, options);

	const query = useInfiniteQuery(
		queryOptions,
		queryClient,
	) as UseInfiniteQueryResult<TData, TError> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};

	query.queryKey = queryOptions.queryKey;

	return query;
}

export const getGetMoviesSearchQueryOptions = <
	TData = Awaited<ReturnType<typeof getMoviesSearch>>,
	TError =
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse,
>(
	params: GetMoviesSearchParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getMoviesSearch>>,
				TError,
				TData
			>
		>;
	},
) => {
	const { query: queryOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getGetMoviesSearchQueryKey(params);

	const queryFn: QueryFunction<Awaited<ReturnType<typeof getMoviesSearch>>> = ({
		signal,
	}) => getMoviesSearch(params, signal);

	return {
		queryKey,
		queryFn,
		staleTime: 10000,
		...queryOptions,
	} as UseQueryOptions<
		Awaited<ReturnType<typeof getMoviesSearch>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetMoviesSearchQueryResult = NonNullable<
	Awaited<ReturnType<typeof getMoviesSearch>>
>;
export type GetMoviesSearchQueryError =
	| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse
	| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse;

export function useGetMoviesSearch<
	TData = Awaited<ReturnType<typeof getMoviesSearch>>,
	TError =
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse,
>(
	params: GetMoviesSearchParams,
	options: {
		query: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getMoviesSearch>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getMoviesSearch>>,
					TError,
					Awaited<ReturnType<typeof getMoviesSearch>>
				>,
				"initialData"
			>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetMoviesSearch<
	TData = Awaited<ReturnType<typeof getMoviesSearch>>,
	TError =
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse,
>(
	params: GetMoviesSearchParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getMoviesSearch>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getMoviesSearch>>,
					TError,
					Awaited<ReturnType<typeof getMoviesSearch>>
				>,
				"initialData"
			>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetMoviesSearch<
	TData = Awaited<ReturnType<typeof getMoviesSearch>>,
	TError =
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse,
>(
	params: GetMoviesSearchParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getMoviesSearch>>,
				TError,
				TData
			>
		>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Search movies via Elasticsearch
 */

export function useGetMoviesSearch<
	TData = Awaited<ReturnType<typeof getMoviesSearch>>,
	TError =
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse,
>(
	params: GetMoviesSearchParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getMoviesSearch>>,
				TError,
				TData
			>
		>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetMoviesSearchQueryOptions(params, options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	query.queryKey = queryOptions.queryKey;

	return query;
}

/**
 * Update fields of a movie using its MongoDB ObjectID
 * @summary Update movie by ID
 */
export const putMoviesId = (
	id: string,
	githubComTeachiesStreamingApInternalDatabaseModelsUpdateMovieRequest: GithubComTeachiesStreamingApInternalDatabaseModelsUpdateMovieRequest,
) => {
	return customInstance<GithubComTeachiesStreamingApInternalDatabaseModelsApiSuccessResponse>(
		{
			url: `/movies/${id}`,
			method: "PUT",
			headers: { "Content-Type": "application/json" },
			data: githubComTeachiesStreamingApInternalDatabaseModelsUpdateMovieRequest,
		},
	);
};

export const getPutMoviesIdMutationOptions = <
	TError =
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof putMoviesId>>,
		TError,
		{
			id: string;
			data: GithubComTeachiesStreamingApInternalDatabaseModelsUpdateMovieRequest;
		},
		TContext
	>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof putMoviesId>>,
	TError,
	{
		id: string;
		data: GithubComTeachiesStreamingApInternalDatabaseModelsUpdateMovieRequest;
	},
	TContext
> => {
	const mutationKey = ["putMoviesId"];
	const { mutation: mutationOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey } };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof putMoviesId>>,
		{
			id: string;
			data: GithubComTeachiesStreamingApInternalDatabaseModelsUpdateMovieRequest;
		}
	> = (props) => {
		const { id, data } = props ?? {};

		return putMoviesId(id, data);
	};

	return { mutationFn, ...mutationOptions };
};

export type PutMoviesIdMutationResult = NonNullable<
	Awaited<ReturnType<typeof putMoviesId>>
>;
export type PutMoviesIdMutationBody =
	GithubComTeachiesStreamingApInternalDatabaseModelsUpdateMovieRequest;
export type PutMoviesIdMutationError =
	| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse
	| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse;

/**
 * @summary Update movie by ID
 */
export const usePutMoviesId = <
	TError =
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof putMoviesId>>,
			TError,
			{
				id: string;
				data: GithubComTeachiesStreamingApInternalDatabaseModelsUpdateMovieRequest;
			},
			TContext
		>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof putMoviesId>>,
	TError,
	{
		id: string;
		data: GithubComTeachiesStreamingApInternalDatabaseModelsUpdateMovieRequest;
	},
	TContext
> => {
	const mutationOptions = getPutMoviesIdMutationOptions(options);

	return useMutation(mutationOptions, queryClient);
};
/**
 * Remove a movie document from the collection by its ObjectID and sync with Elasticsearch.
 * @summary Delete a movie
 */
export const deleteMoviesId = (id: string) => {
	return customInstance<GithubComTeachiesStreamingApInternalDatabaseModelsApiSuccessResponse>(
		{ url: `/movies/${id}`, method: "DELETE" },
	);
};

export const getDeleteMoviesIdMutationOptions = <
	TError =
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof deleteMoviesId>>,
		TError,
		{ id: string },
		TContext
	>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof deleteMoviesId>>,
	TError,
	{ id: string },
	TContext
> => {
	const mutationKey = ["deleteMoviesId"];
	const { mutation: mutationOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey } };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof deleteMoviesId>>,
		{ id: string }
	> = (props) => {
		const { id } = props ?? {};

		return deleteMoviesId(id);
	};

	return { mutationFn, ...mutationOptions };
};

export type DeleteMoviesIdMutationResult = NonNullable<
	Awaited<ReturnType<typeof deleteMoviesId>>
>;

export type DeleteMoviesIdMutationError =
	| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse
	| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse
	| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse;

/**
 * @summary Delete a movie
 */
export const useDeleteMoviesId = <
	TError =
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof deleteMoviesId>>,
			TError,
			{ id: string },
			TContext
		>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof deleteMoviesId>>,
	TError,
	{ id: string },
	TContext
> => {
	const mutationOptions = getDeleteMoviesIdMutationOptions(options);

	return useMutation(mutationOptions, queryClient);
};
/**
 * Retrieve a movie by its IMDB ID string (e.g., tt0790724)
 * @summary Get a single movie
 */
export const getMoviesImdbId = (imdbId: string, signal?: AbortSignal) => {
	return customInstance<GithubComTeachiesStreamingApInternalDatabaseModelsApiSuccessResponse>(
		{ url: `/movies/${imdbId}`, method: "GET", signal },
	);
};

export const getGetMoviesImdbIdInfiniteQueryKey = (imdbId?: string) => {
	return ["infinate", `/movies/${imdbId}`] as const;
};

export const getGetMoviesImdbIdQueryKey = (imdbId?: string) => {
	return [`/movies/${imdbId}`] as const;
};

export const getGetMoviesImdbIdInfiniteQueryOptions = <
	TData = InfiniteData<Awaited<ReturnType<typeof getMoviesImdbId>>>,
	TError =
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse,
>(
	imdbId: string,
	options?: {
		query?: Partial<
			UseInfiniteQueryOptions<
				Awaited<ReturnType<typeof getMoviesImdbId>>,
				TError,
				TData
			>
		>;
	},
) => {
	const { query: queryOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ?? getGetMoviesImdbIdInfiniteQueryKey(imdbId);

	const queryFn: QueryFunction<Awaited<ReturnType<typeof getMoviesImdbId>>> = ({
		signal,
	}) => getMoviesImdbId(imdbId, signal);

	return {
		queryKey,
		queryFn,
		enabled: !!imdbId,
		staleTime: 10000,
		...queryOptions,
	} as UseInfiniteQueryOptions<
		Awaited<ReturnType<typeof getMoviesImdbId>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetMoviesImdbIdInfiniteQueryResult = NonNullable<
	Awaited<ReturnType<typeof getMoviesImdbId>>
>;
export type GetMoviesImdbIdInfiniteQueryError =
	| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse
	| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse
	| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse;

export function useGetMoviesImdbIdInfinite<
	TData = InfiniteData<Awaited<ReturnType<typeof getMoviesImdbId>>>,
	TError =
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse,
>(
	imdbId: string,
	options: {
		query: Partial<
			UseInfiniteQueryOptions<
				Awaited<ReturnType<typeof getMoviesImdbId>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getMoviesImdbId>>,
					TError,
					Awaited<ReturnType<typeof getMoviesImdbId>>
				>,
				"initialData"
			>;
	},
	queryClient?: QueryClient,
): DefinedUseInfiniteQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetMoviesImdbIdInfinite<
	TData = InfiniteData<Awaited<ReturnType<typeof getMoviesImdbId>>>,
	TError =
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse,
>(
	imdbId: string,
	options?: {
		query?: Partial<
			UseInfiniteQueryOptions<
				Awaited<ReturnType<typeof getMoviesImdbId>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getMoviesImdbId>>,
					TError,
					Awaited<ReturnType<typeof getMoviesImdbId>>
				>,
				"initialData"
			>;
	},
	queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetMoviesImdbIdInfinite<
	TData = InfiniteData<Awaited<ReturnType<typeof getMoviesImdbId>>>,
	TError =
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse,
>(
	imdbId: string,
	options?: {
		query?: Partial<
			UseInfiniteQueryOptions<
				Awaited<ReturnType<typeof getMoviesImdbId>>,
				TError,
				TData
			>
		>;
	},
	queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get a single movie
 */

export function useGetMoviesImdbIdInfinite<
	TData = InfiniteData<Awaited<ReturnType<typeof getMoviesImdbId>>>,
	TError =
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse,
>(
	imdbId: string,
	options?: {
		query?: Partial<
			UseInfiniteQueryOptions<
				Awaited<ReturnType<typeof getMoviesImdbId>>,
				TError,
				TData
			>
		>;
	},
	queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetMoviesImdbIdInfiniteQueryOptions(imdbId, options);

	const query = useInfiniteQuery(
		queryOptions,
		queryClient,
	) as UseInfiniteQueryResult<TData, TError> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};

	query.queryKey = queryOptions.queryKey;

	return query;
}

export const getGetMoviesImdbIdQueryOptions = <
	TData = Awaited<ReturnType<typeof getMoviesImdbId>>,
	TError =
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse,
>(
	imdbId: string,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getMoviesImdbId>>,
				TError,
				TData
			>
		>;
	},
) => {
	const { query: queryOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getGetMoviesImdbIdQueryKey(imdbId);

	const queryFn: QueryFunction<Awaited<ReturnType<typeof getMoviesImdbId>>> = ({
		signal,
	}) => getMoviesImdbId(imdbId, signal);

	return {
		queryKey,
		queryFn,
		enabled: !!imdbId,
		staleTime: 10000,
		...queryOptions,
	} as UseQueryOptions<
		Awaited<ReturnType<typeof getMoviesImdbId>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetMoviesImdbIdQueryResult = NonNullable<
	Awaited<ReturnType<typeof getMoviesImdbId>>
>;
export type GetMoviesImdbIdQueryError =
	| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse
	| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse
	| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse;

export function useGetMoviesImdbId<
	TData = Awaited<ReturnType<typeof getMoviesImdbId>>,
	TError =
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse,
>(
	imdbId: string,
	options: {
		query: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getMoviesImdbId>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getMoviesImdbId>>,
					TError,
					Awaited<ReturnType<typeof getMoviesImdbId>>
				>,
				"initialData"
			>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetMoviesImdbId<
	TData = Awaited<ReturnType<typeof getMoviesImdbId>>,
	TError =
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse,
>(
	imdbId: string,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getMoviesImdbId>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getMoviesImdbId>>,
					TError,
					Awaited<ReturnType<typeof getMoviesImdbId>>
				>,
				"initialData"
			>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetMoviesImdbId<
	TData = Awaited<ReturnType<typeof getMoviesImdbId>>,
	TError =
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse,
>(
	imdbId: string,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getMoviesImdbId>>,
				TError,
				TData
			>
		>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get a single movie
 */

export function useGetMoviesImdbId<
	TData = Awaited<ReturnType<typeof getMoviesImdbId>>,
	TError =
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse,
>(
	imdbId: string,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getMoviesImdbId>>,
				TError,
				TData
			>
		>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetMoviesImdbIdQueryOptions(imdbId, options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	query.queryKey = queryOptions.queryKey;

	return query;
}

/**
 * Updates a movie's admin review text and uses Gemini AI to automatically assign a ranking.
 * @summary Update movie review with AI analysis
 */
export const patchMoviesImdbIdReview = (
	imdbId: string,
	patchMoviesImdbIdReviewBody: PatchMoviesImdbIdReviewBody,
) => {
	return customInstance<GithubComTeachiesStreamingApInternalDatabaseModelsApiSuccessResponse>(
		{
			url: `/movies/${imdbId}/review`,
			method: "PATCH",
			headers: { "Content-Type": "application/json" },
			data: patchMoviesImdbIdReviewBody,
		},
	);
};

export const getPatchMoviesImdbIdReviewMutationOptions = <
	TError = GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof patchMoviesImdbIdReview>>,
		TError,
		{ imdbId: string; data: PatchMoviesImdbIdReviewBody },
		TContext
	>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof patchMoviesImdbIdReview>>,
	TError,
	{ imdbId: string; data: PatchMoviesImdbIdReviewBody },
	TContext
> => {
	const mutationKey = ["patchMoviesImdbIdReview"];
	const { mutation: mutationOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey } };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof patchMoviesImdbIdReview>>,
		{ imdbId: string; data: PatchMoviesImdbIdReviewBody }
	> = (props) => {
		const { imdbId, data } = props ?? {};

		return patchMoviesImdbIdReview(imdbId, data);
	};

	return { mutationFn, ...mutationOptions };
};

export type PatchMoviesImdbIdReviewMutationResult = NonNullable<
	Awaited<ReturnType<typeof patchMoviesImdbIdReview>>
>;
export type PatchMoviesImdbIdReviewMutationBody = PatchMoviesImdbIdReviewBody;
export type PatchMoviesImdbIdReviewMutationError =
	GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse;

/**
 * @summary Update movie review with AI analysis
 */
export const usePatchMoviesImdbIdReview = <
	TError = GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof patchMoviesImdbIdReview>>,
			TError,
			{ imdbId: string; data: PatchMoviesImdbIdReviewBody },
			TContext
		>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof patchMoviesImdbIdReview>>,
	TError,
	{ imdbId: string; data: PatchMoviesImdbIdReviewBody },
	TContext
> => {
	const mutationOptions = getPatchMoviesImdbIdReviewMutationOptions(options);

	return useMutation(mutationOptions, queryClient);
};
