/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Streaming App API
 * API for streaming application with WebSocket support
 * OpenAPI spec version: 1.0
 */

import type {
	DataTag,
	DefinedInitialDataOptions,
	DefinedUseInfiniteQueryResult,
	DefinedUseQueryResult,
	InfiniteData,
	MutationFunction,
	QueryClient,
	QueryFunction,
	QueryKey,
	UndefinedInitialDataOptions,
	UseInfiniteQueryOptions,
	UseInfiniteQueryResult,
	UseMutationOptions,
	UseMutationResult,
	UseQueryOptions,
	UseQueryResult,
} from "@tanstack/react-query";
import { useInfiniteQuery, useMutation, useQuery } from "@tanstack/react-query";
import { customInstance } from "../../client";
import type {
	GetUsersParams,
	GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse,
	GithubComTeachiesStreamingApInternalDatabaseModelsApiSuccessResponse,
	PatchUsersIdBody,
} from "../../models";

/**
 * Retrieves a paginated list of users with filtering by email, first name, and last name.
 * @summary Search and Filter users
 */
export const getUsers = (params?: GetUsersParams, signal?: AbortSignal) => {
	return customInstance<GithubComTeachiesStreamingApInternalDatabaseModelsApiSuccessResponse>(
		{ url: `/users`, method: "GET", params, signal },
	);
};

export const getGetUsersInfiniteQueryKey = (params?: GetUsersParams) => {
	return ["infinate", `/users`, ...(params ? [params] : [])] as const;
};

export const getGetUsersQueryKey = (params?: GetUsersParams) => {
	return [`/users`, ...(params ? [params] : [])] as const;
};

export const getGetUsersInfiniteQueryOptions = <
	TData = InfiniteData<
		Awaited<ReturnType<typeof getUsers>>,
		GetUsersParams["page"]
	>,
	TError =
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse,
>(
	params?: GetUsersParams,
	options?: {
		query?: Partial<
			UseInfiniteQueryOptions<
				Awaited<ReturnType<typeof getUsers>>,
				TError,
				TData,
				Awaited<ReturnType<typeof getUsers>>,
				QueryKey,
				GetUsersParams["page"]
			>
		>;
	},
) => {
	const { query: queryOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ?? getGetUsersInfiniteQueryKey(params);

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof getUsers>>,
		QueryKey,
		GetUsersParams["page"]
	> = ({ signal, pageParam }) =>
		getUsers({ ...params, page: pageParam || params?.page }, signal);

	return {
		queryKey,
		queryFn,
		staleTime: 10000,
		...queryOptions,
	} as UseInfiniteQueryOptions<
		Awaited<ReturnType<typeof getUsers>>,
		TError,
		TData,
		Awaited<ReturnType<typeof getUsers>>,
		QueryKey,
		GetUsersParams["page"]
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetUsersInfiniteQueryResult = NonNullable<
	Awaited<ReturnType<typeof getUsers>>
>;
export type GetUsersInfiniteQueryError =
	| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse
	| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse;

export function useGetUsersInfinite<
	TData = InfiniteData<
		Awaited<ReturnType<typeof getUsers>>,
		GetUsersParams["page"]
	>,
	TError =
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse,
>(
	params: undefined | GetUsersParams,
	options: {
		query: Partial<
			UseInfiniteQueryOptions<
				Awaited<ReturnType<typeof getUsers>>,
				TError,
				TData,
				Awaited<ReturnType<typeof getUsers>>,
				QueryKey,
				GetUsersParams["page"]
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getUsers>>,
					TError,
					Awaited<ReturnType<typeof getUsers>>,
					QueryKey
				>,
				"initialData"
			>;
	},
	queryClient?: QueryClient,
): DefinedUseInfiniteQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetUsersInfinite<
	TData = InfiniteData<
		Awaited<ReturnType<typeof getUsers>>,
		GetUsersParams["page"]
	>,
	TError =
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse,
>(
	params?: GetUsersParams,
	options?: {
		query?: Partial<
			UseInfiniteQueryOptions<
				Awaited<ReturnType<typeof getUsers>>,
				TError,
				TData,
				Awaited<ReturnType<typeof getUsers>>,
				QueryKey,
				GetUsersParams["page"]
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getUsers>>,
					TError,
					Awaited<ReturnType<typeof getUsers>>,
					QueryKey
				>,
				"initialData"
			>;
	},
	queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetUsersInfinite<
	TData = InfiniteData<
		Awaited<ReturnType<typeof getUsers>>,
		GetUsersParams["page"]
	>,
	TError =
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse,
>(
	params?: GetUsersParams,
	options?: {
		query?: Partial<
			UseInfiniteQueryOptions<
				Awaited<ReturnType<typeof getUsers>>,
				TError,
				TData,
				Awaited<ReturnType<typeof getUsers>>,
				QueryKey,
				GetUsersParams["page"]
			>
		>;
	},
	queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Search and Filter users
 */

export function useGetUsersInfinite<
	TData = InfiniteData<
		Awaited<ReturnType<typeof getUsers>>,
		GetUsersParams["page"]
	>,
	TError =
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse,
>(
	params?: GetUsersParams,
	options?: {
		query?: Partial<
			UseInfiniteQueryOptions<
				Awaited<ReturnType<typeof getUsers>>,
				TError,
				TData,
				Awaited<ReturnType<typeof getUsers>>,
				QueryKey,
				GetUsersParams["page"]
			>
		>;
	},
	queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetUsersInfiniteQueryOptions(params, options);

	const query = useInfiniteQuery(
		queryOptions,
		queryClient,
	) as UseInfiniteQueryResult<TData, TError> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};

	query.queryKey = queryOptions.queryKey;

	return query;
}

export const getGetUsersQueryOptions = <
	TData = Awaited<ReturnType<typeof getUsers>>,
	TError =
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse,
>(
	params?: GetUsersParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getUsers>>, TError, TData>
		>;
	},
) => {
	const { query: queryOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getGetUsersQueryKey(params);

	const queryFn: QueryFunction<Awaited<ReturnType<typeof getUsers>>> = ({
		signal,
	}) => getUsers(params, signal);

	return {
		queryKey,
		queryFn,
		staleTime: 10000,
		...queryOptions,
	} as UseQueryOptions<Awaited<ReturnType<typeof getUsers>>, TError, TData> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};
};

export type GetUsersQueryResult = NonNullable<
	Awaited<ReturnType<typeof getUsers>>
>;
export type GetUsersQueryError =
	| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse
	| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse;

export function useGetUsers<
	TData = Awaited<ReturnType<typeof getUsers>>,
	TError =
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse,
>(
	params: undefined | GetUsersParams,
	options: {
		query: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getUsers>>, TError, TData>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getUsers>>,
					TError,
					Awaited<ReturnType<typeof getUsers>>
				>,
				"initialData"
			>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetUsers<
	TData = Awaited<ReturnType<typeof getUsers>>,
	TError =
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse,
>(
	params?: GetUsersParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getUsers>>, TError, TData>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getUsers>>,
					TError,
					Awaited<ReturnType<typeof getUsers>>
				>,
				"initialData"
			>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetUsers<
	TData = Awaited<ReturnType<typeof getUsers>>,
	TError =
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse,
>(
	params?: GetUsersParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getUsers>>, TError, TData>
		>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Search and Filter users
 */

export function useGetUsers<
	TData = Awaited<ReturnType<typeof getUsers>>,
	TError =
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse,
>(
	params?: GetUsersParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getUsers>>, TError, TData>
		>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetUsersQueryOptions(params, options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	query.queryKey = queryOptions.queryKey;

	return query;
}

/**
 * Removes a user from the database. Restricted to Admins.
 * @summary Delete a user
 */
export const deleteUsersId = (id: string) => {
	return customInstance<GithubComTeachiesStreamingApInternalDatabaseModelsApiSuccessResponse>(
		{ url: `/users/${id}`, method: "DELETE" },
	);
};

export const getDeleteUsersIdMutationOptions = <
	TError =
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof deleteUsersId>>,
		TError,
		{ id: string },
		TContext
	>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof deleteUsersId>>,
	TError,
	{ id: string },
	TContext
> => {
	const mutationKey = ["deleteUsersId"];
	const { mutation: mutationOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey } };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof deleteUsersId>>,
		{ id: string }
	> = (props) => {
		const { id } = props ?? {};

		return deleteUsersId(id);
	};

	return { mutationFn, ...mutationOptions };
};

export type DeleteUsersIdMutationResult = NonNullable<
	Awaited<ReturnType<typeof deleteUsersId>>
>;

export type DeleteUsersIdMutationError =
	| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse
	| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse
	| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse;

/**
 * @summary Delete a user
 */
export const useDeleteUsersId = <
	TError =
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof deleteUsersId>>,
			TError,
			{ id: string },
			TContext
		>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof deleteUsersId>>,
	TError,
	{ id: string },
	TContext
> => {
	const mutationOptions = getDeleteUsersIdMutationOptions(options);

	return useMutation(mutationOptions, queryClient);
};
/**
 * Updates specific fields of a user record using BSON $set logic.
 * @summary Update user details
 */
export const patchUsersId = (
	id: string,
	patchUsersIdBody: PatchUsersIdBody,
) => {
	return customInstance<GithubComTeachiesStreamingApInternalDatabaseModelsApiSuccessResponse>(
		{
			url: `/users/${id}`,
			method: "PATCH",
			headers: { "Content-Type": "application/json" },
			data: patchUsersIdBody,
		},
	);
};

export const getPatchUsersIdMutationOptions = <
	TError =
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof patchUsersId>>,
		TError,
		{ id: string; data: PatchUsersIdBody },
		TContext
	>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof patchUsersId>>,
	TError,
	{ id: string; data: PatchUsersIdBody },
	TContext
> => {
	const mutationKey = ["patchUsersId"];
	const { mutation: mutationOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey } };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof patchUsersId>>,
		{ id: string; data: PatchUsersIdBody }
	> = (props) => {
		const { id, data } = props ?? {};

		return patchUsersId(id, data);
	};

	return { mutationFn, ...mutationOptions };
};

export type PatchUsersIdMutationResult = NonNullable<
	Awaited<ReturnType<typeof patchUsersId>>
>;
export type PatchUsersIdMutationBody = PatchUsersIdBody;
export type PatchUsersIdMutationError =
	| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse
	| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse;

/**
 * @summary Update user details
 */
export const usePatchUsersId = <
	TError =
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse
		| GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof patchUsersId>>,
			TError,
			{ id: string; data: PatchUsersIdBody },
			TContext
		>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof patchUsersId>>,
	TError,
	{ id: string; data: PatchUsersIdBody },
	TContext
> => {
	const mutationOptions = getPatchUsersIdMutationOptions(options);

	return useMutation(mutationOptions, queryClient);
};
