/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Streaming App API
 * API for streaming application with WebSocket support
 * OpenAPI spec version: 1.0
 */

import type {
	DataTag,
	DefinedInitialDataOptions,
	DefinedUseInfiniteQueryResult,
	DefinedUseQueryResult,
	InfiniteData,
	QueryClient,
	QueryFunction,
	QueryKey,
	UndefinedInitialDataOptions,
	UseInfiniteQueryOptions,
	UseInfiniteQueryResult,
	UseQueryOptions,
	UseQueryResult,
} from "@tanstack/react-query";
import { useInfiniteQuery, useQuery } from "@tanstack/react-query";
import { customInstance } from "../../client";
import type {
	GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse,
	GithubComTeachiesStreamingApInternalDatabaseModelsApiSuccessResponse,
} from "../../models";

/**
 * Retrieves the full list of unique genres from the database.
 * @summary Get all available genres
 */
export const getMoviesGenres = (signal?: AbortSignal) => {
	return customInstance<GithubComTeachiesStreamingApInternalDatabaseModelsApiSuccessResponse>(
		{ url: `/movies/genres`, method: "GET", signal },
	);
};

export const getGetMoviesGenresInfiniteQueryKey = () => {
	return ["infinate", `/movies/genres`] as const;
};

export const getGetMoviesGenresQueryKey = () => {
	return [`/movies/genres`] as const;
};

export const getGetMoviesGenresInfiniteQueryOptions = <
	TData = InfiniteData<Awaited<ReturnType<typeof getMoviesGenres>>>,
	TError = GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse,
>(options?: {
	query?: Partial<
		UseInfiniteQueryOptions<
			Awaited<ReturnType<typeof getMoviesGenres>>,
			TError,
			TData
		>
	>;
}) => {
	const { query: queryOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ?? getGetMoviesGenresInfiniteQueryKey();

	const queryFn: QueryFunction<Awaited<ReturnType<typeof getMoviesGenres>>> = ({
		signal,
	}) => getMoviesGenres(signal);

	return {
		queryKey,
		queryFn,
		staleTime: 10000,
		...queryOptions,
	} as UseInfiniteQueryOptions<
		Awaited<ReturnType<typeof getMoviesGenres>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetMoviesGenresInfiniteQueryResult = NonNullable<
	Awaited<ReturnType<typeof getMoviesGenres>>
>;
export type GetMoviesGenresInfiniteQueryError =
	GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse;

export function useGetMoviesGenresInfinite<
	TData = InfiniteData<Awaited<ReturnType<typeof getMoviesGenres>>>,
	TError = GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse,
>(
	options: {
		query: Partial<
			UseInfiniteQueryOptions<
				Awaited<ReturnType<typeof getMoviesGenres>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getMoviesGenres>>,
					TError,
					Awaited<ReturnType<typeof getMoviesGenres>>
				>,
				"initialData"
			>;
	},
	queryClient?: QueryClient,
): DefinedUseInfiniteQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetMoviesGenresInfinite<
	TData = InfiniteData<Awaited<ReturnType<typeof getMoviesGenres>>>,
	TError = GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse,
>(
	options?: {
		query?: Partial<
			UseInfiniteQueryOptions<
				Awaited<ReturnType<typeof getMoviesGenres>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getMoviesGenres>>,
					TError,
					Awaited<ReturnType<typeof getMoviesGenres>>
				>,
				"initialData"
			>;
	},
	queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetMoviesGenresInfinite<
	TData = InfiniteData<Awaited<ReturnType<typeof getMoviesGenres>>>,
	TError = GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse,
>(
	options?: {
		query?: Partial<
			UseInfiniteQueryOptions<
				Awaited<ReturnType<typeof getMoviesGenres>>,
				TError,
				TData
			>
		>;
	},
	queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get all available genres
 */

export function useGetMoviesGenresInfinite<
	TData = InfiniteData<Awaited<ReturnType<typeof getMoviesGenres>>>,
	TError = GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse,
>(
	options?: {
		query?: Partial<
			UseInfiniteQueryOptions<
				Awaited<ReturnType<typeof getMoviesGenres>>,
				TError,
				TData
			>
		>;
	},
	queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetMoviesGenresInfiniteQueryOptions(options);

	const query = useInfiniteQuery(
		queryOptions,
		queryClient,
	) as UseInfiniteQueryResult<TData, TError> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};

	query.queryKey = queryOptions.queryKey;

	return query;
}

export const getGetMoviesGenresQueryOptions = <
	TData = Awaited<ReturnType<typeof getMoviesGenres>>,
	TError = GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse,
>(options?: {
	query?: Partial<
		UseQueryOptions<Awaited<ReturnType<typeof getMoviesGenres>>, TError, TData>
	>;
}) => {
	const { query: queryOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getGetMoviesGenresQueryKey();

	const queryFn: QueryFunction<Awaited<ReturnType<typeof getMoviesGenres>>> = ({
		signal,
	}) => getMoviesGenres(signal);

	return {
		queryKey,
		queryFn,
		staleTime: 10000,
		...queryOptions,
	} as UseQueryOptions<
		Awaited<ReturnType<typeof getMoviesGenres>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetMoviesGenresQueryResult = NonNullable<
	Awaited<ReturnType<typeof getMoviesGenres>>
>;
export type GetMoviesGenresQueryError =
	GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse;

export function useGetMoviesGenres<
	TData = Awaited<ReturnType<typeof getMoviesGenres>>,
	TError = GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse,
>(
	options: {
		query: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getMoviesGenres>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getMoviesGenres>>,
					TError,
					Awaited<ReturnType<typeof getMoviesGenres>>
				>,
				"initialData"
			>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetMoviesGenres<
	TData = Awaited<ReturnType<typeof getMoviesGenres>>,
	TError = GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getMoviesGenres>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getMoviesGenres>>,
					TError,
					Awaited<ReturnType<typeof getMoviesGenres>>
				>,
				"initialData"
			>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetMoviesGenres<
	TData = Awaited<ReturnType<typeof getMoviesGenres>>,
	TError = GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getMoviesGenres>>,
				TError,
				TData
			>
		>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get all available genres
 */

export function useGetMoviesGenres<
	TData = Awaited<ReturnType<typeof getMoviesGenres>>,
	TError = GithubComTeachiesStreamingApInternalDatabaseModelsApiErrorResponse,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getMoviesGenres>>,
				TError,
				TData
			>
		>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetMoviesGenresQueryOptions(options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	query.queryKey = queryOptions.queryKey;

	return query;
}
