/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as DiscoveryRouteImport } from './routes/discovery'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MoviesIndexRouteImport } from './routes/movies/index'
import { Route as LibraryIndexRouteImport } from './routes/library/index'
import { Route as MusicMusicidRouteImport } from './routes/music/$musicid'
import { Route as MoviesMovieIdRouteImport } from './routes/movies/$movieId'
import { Route as LibraryProfileRouteImport } from './routes/library/profile'
import { Route as ExploreSectionRouteImport } from './routes/explore/$section'
import { Route as AuthVerifyRouteImport } from './routes/auth/verify'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as demoHomeDemoIndexRouteImport } from './routes/(demo)/home-demo/index'
import { Route as demoDemoIndexRouteImport } from './routes/(demo)/demo/index'
import { Route as demoDemoTanstackQueryRouteImport } from './routes/(demo)/demo/tanstack-query'
import { Route as demoDemoTanchatRouteImport } from './routes/(demo)/demo/tanchat'
import { Route as demoDemoTableRouteImport } from './routes/(demo)/demo/table'
import { Route as demoDemoStorybookRouteImport } from './routes/(demo)/demo/storybook'
import { Route as demoDemoStoreRouteImport } from './routes/(demo)/demo/store'
import { Route as demoExampleGuitarsIndexRouteImport } from './routes/(demo)/example.guitars/index'
import { Route as demoExampleGuitarsGuitarIdRouteImport } from './routes/(demo)/example.guitars/$guitarId'
import { Route as demoDemoStartServerFuncsRouteImport } from './routes/(demo)/demo/start.server-funcs'
import { Route as demoDemoStartApiRequestRouteImport } from './routes/(demo)/demo/start.api-request'
import { Route as demoDemoSentryTestingRouteImport } from './routes/(demo)/demo/sentry.testing'
import { Route as demoDemoApiTqTodosRouteImport } from './routes/(demo)/demo/api.tq-todos'
import { Route as demoDemoApiTanchatRouteImport } from './routes/(demo)/demo/api.tanchat'
import { Route as demoDemoApiNamesRouteImport } from './routes/(demo)/demo/api.names'
import { Route as demoDemoStartSsrIndexRouteImport } from './routes/(demo)/demo/start.ssr.index'
import { Route as demoDemoStartSsrSpaModeRouteImport } from './routes/(demo)/demo/start.ssr.spa-mode'
import { Route as demoDemoStartSsrFullSsrRouteImport } from './routes/(demo)/demo/start.ssr.full-ssr'
import { Route as demoDemoStartSsrDataOnlyRouteImport } from './routes/(demo)/demo/start.ssr.data-only'

const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoveryRoute = DiscoveryRouteImport.update({
  id: '/discovery',
  path: '/discovery',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MoviesIndexRoute = MoviesIndexRouteImport.update({
  id: '/movies/',
  path: '/movies/',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryIndexRoute = LibraryIndexRouteImport.update({
  id: '/library/',
  path: '/library/',
  getParentRoute: () => rootRouteImport,
} as any)
const MusicMusicidRoute = MusicMusicidRouteImport.update({
  id: '/music/$musicid',
  path: '/music/$musicid',
  getParentRoute: () => rootRouteImport,
} as any)
const MoviesMovieIdRoute = MoviesMovieIdRouteImport.update({
  id: '/movies/$movieId',
  path: '/movies/$movieId',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryProfileRoute = LibraryProfileRouteImport.update({
  id: '/library/profile',
  path: '/library/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreSectionRoute = ExploreSectionRouteImport.update({
  id: '/explore/$section',
  path: '/explore/$section',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyRoute = AuthVerifyRouteImport.update({
  id: '/auth/verify',
  path: '/auth/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const demoHomeDemoIndexRoute = demoHomeDemoIndexRouteImport.update({
  id: '/(demo)/home-demo/',
  path: '/home-demo/',
  getParentRoute: () => rootRouteImport,
} as any)
const demoDemoIndexRoute = demoDemoIndexRouteImport.update({
  id: '/(demo)/demo/',
  path: '/demo/',
  getParentRoute: () => rootRouteImport,
} as any)
const demoDemoTanstackQueryRoute = demoDemoTanstackQueryRouteImport.update({
  id: '/(demo)/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const demoDemoTanchatRoute = demoDemoTanchatRouteImport.update({
  id: '/(demo)/demo/tanchat',
  path: '/demo/tanchat',
  getParentRoute: () => rootRouteImport,
} as any)
const demoDemoTableRoute = demoDemoTableRouteImport.update({
  id: '/(demo)/demo/table',
  path: '/demo/table',
  getParentRoute: () => rootRouteImport,
} as any)
const demoDemoStorybookRoute = demoDemoStorybookRouteImport.update({
  id: '/(demo)/demo/storybook',
  path: '/demo/storybook',
  getParentRoute: () => rootRouteImport,
} as any)
const demoDemoStoreRoute = demoDemoStoreRouteImport.update({
  id: '/(demo)/demo/store',
  path: '/demo/store',
  getParentRoute: () => rootRouteImport,
} as any)
const demoExampleGuitarsIndexRoute = demoExampleGuitarsIndexRouteImport.update({
  id: '/(demo)/example/guitars/',
  path: '/example/guitars/',
  getParentRoute: () => rootRouteImport,
} as any)
const demoExampleGuitarsGuitarIdRoute =
  demoExampleGuitarsGuitarIdRouteImport.update({
    id: '/(demo)/example/guitars/$guitarId',
    path: '/example/guitars/$guitarId',
    getParentRoute: () => rootRouteImport,
  } as any)
const demoDemoStartServerFuncsRoute =
  demoDemoStartServerFuncsRouteImport.update({
    id: '/(demo)/demo/start/server-funcs',
    path: '/demo/start/server-funcs',
    getParentRoute: () => rootRouteImport,
  } as any)
const demoDemoStartApiRequestRoute = demoDemoStartApiRequestRouteImport.update({
  id: '/(demo)/demo/start/api-request',
  path: '/demo/start/api-request',
  getParentRoute: () => rootRouteImport,
} as any)
const demoDemoSentryTestingRoute = demoDemoSentryTestingRouteImport.update({
  id: '/(demo)/demo/sentry/testing',
  path: '/demo/sentry/testing',
  getParentRoute: () => rootRouteImport,
} as any)
const demoDemoApiTqTodosRoute = demoDemoApiTqTodosRouteImport.update({
  id: '/(demo)/demo/api/tq-todos',
  path: '/demo/api/tq-todos',
  getParentRoute: () => rootRouteImport,
} as any)
const demoDemoApiTanchatRoute = demoDemoApiTanchatRouteImport.update({
  id: '/(demo)/demo/api/tanchat',
  path: '/demo/api/tanchat',
  getParentRoute: () => rootRouteImport,
} as any)
const demoDemoApiNamesRoute = demoDemoApiNamesRouteImport.update({
  id: '/(demo)/demo/api/names',
  path: '/demo/api/names',
  getParentRoute: () => rootRouteImport,
} as any)
const demoDemoStartSsrIndexRoute = demoDemoStartSsrIndexRouteImport.update({
  id: '/(demo)/demo/start/ssr/',
  path: '/demo/start/ssr/',
  getParentRoute: () => rootRouteImport,
} as any)
const demoDemoStartSsrSpaModeRoute = demoDemoStartSsrSpaModeRouteImport.update({
  id: '/(demo)/demo/start/ssr/spa-mode',
  path: '/demo/start/ssr/spa-mode',
  getParentRoute: () => rootRouteImport,
} as any)
const demoDemoStartSsrFullSsrRoute = demoDemoStartSsrFullSsrRouteImport.update({
  id: '/(demo)/demo/start/ssr/full-ssr',
  path: '/demo/start/ssr/full-ssr',
  getParentRoute: () => rootRouteImport,
} as any)
const demoDemoStartSsrDataOnlyRoute =
  demoDemoStartSsrDataOnlyRouteImport.update({
    id: '/(demo)/demo/start/ssr/data-only',
    path: '/demo/start/ssr/data-only',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/discovery': typeof DiscoveryRoute
  '/pricing': typeof PricingRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/explore/$section': typeof ExploreSectionRoute
  '/library/profile': typeof LibraryProfileRoute
  '/movies/$movieId': typeof MoviesMovieIdRoute
  '/music/$musicid': typeof MusicMusicidRoute
  '/library': typeof LibraryIndexRoute
  '/movies': typeof MoviesIndexRoute
  '/demo/store': typeof demoDemoStoreRoute
  '/demo/storybook': typeof demoDemoStorybookRoute
  '/demo/table': typeof demoDemoTableRoute
  '/demo/tanchat': typeof demoDemoTanchatRoute
  '/demo/tanstack-query': typeof demoDemoTanstackQueryRoute
  '/demo': typeof demoDemoIndexRoute
  '/home-demo': typeof demoHomeDemoIndexRoute
  '/demo/api/names': typeof demoDemoApiNamesRoute
  '/demo/api/tanchat': typeof demoDemoApiTanchatRoute
  '/demo/api/tq-todos': typeof demoDemoApiTqTodosRoute
  '/demo/sentry/testing': typeof demoDemoSentryTestingRoute
  '/demo/start/api-request': typeof demoDemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof demoDemoStartServerFuncsRoute
  '/example/guitars/$guitarId': typeof demoExampleGuitarsGuitarIdRoute
  '/example/guitars': typeof demoExampleGuitarsIndexRoute
  '/demo/start/ssr/data-only': typeof demoDemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof demoDemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof demoDemoStartSsrSpaModeRoute
  '/demo/start/ssr': typeof demoDemoStartSsrIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/discovery': typeof DiscoveryRoute
  '/pricing': typeof PricingRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/explore/$section': typeof ExploreSectionRoute
  '/library/profile': typeof LibraryProfileRoute
  '/movies/$movieId': typeof MoviesMovieIdRoute
  '/music/$musicid': typeof MusicMusicidRoute
  '/library': typeof LibraryIndexRoute
  '/movies': typeof MoviesIndexRoute
  '/demo/store': typeof demoDemoStoreRoute
  '/demo/storybook': typeof demoDemoStorybookRoute
  '/demo/table': typeof demoDemoTableRoute
  '/demo/tanchat': typeof demoDemoTanchatRoute
  '/demo/tanstack-query': typeof demoDemoTanstackQueryRoute
  '/demo': typeof demoDemoIndexRoute
  '/home-demo': typeof demoHomeDemoIndexRoute
  '/demo/api/names': typeof demoDemoApiNamesRoute
  '/demo/api/tanchat': typeof demoDemoApiTanchatRoute
  '/demo/api/tq-todos': typeof demoDemoApiTqTodosRoute
  '/demo/sentry/testing': typeof demoDemoSentryTestingRoute
  '/demo/start/api-request': typeof demoDemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof demoDemoStartServerFuncsRoute
  '/example/guitars/$guitarId': typeof demoExampleGuitarsGuitarIdRoute
  '/example/guitars': typeof demoExampleGuitarsIndexRoute
  '/demo/start/ssr/data-only': typeof demoDemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof demoDemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof demoDemoStartSsrSpaModeRoute
  '/demo/start/ssr': typeof demoDemoStartSsrIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/discovery': typeof DiscoveryRoute
  '/pricing': typeof PricingRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/explore/$section': typeof ExploreSectionRoute
  '/library/profile': typeof LibraryProfileRoute
  '/movies/$movieId': typeof MoviesMovieIdRoute
  '/music/$musicid': typeof MusicMusicidRoute
  '/library/': typeof LibraryIndexRoute
  '/movies/': typeof MoviesIndexRoute
  '/(demo)/demo/store': typeof demoDemoStoreRoute
  '/(demo)/demo/storybook': typeof demoDemoStorybookRoute
  '/(demo)/demo/table': typeof demoDemoTableRoute
  '/(demo)/demo/tanchat': typeof demoDemoTanchatRoute
  '/(demo)/demo/tanstack-query': typeof demoDemoTanstackQueryRoute
  '/(demo)/demo/': typeof demoDemoIndexRoute
  '/(demo)/home-demo/': typeof demoHomeDemoIndexRoute
  '/(demo)/demo/api/names': typeof demoDemoApiNamesRoute
  '/(demo)/demo/api/tanchat': typeof demoDemoApiTanchatRoute
  '/(demo)/demo/api/tq-todos': typeof demoDemoApiTqTodosRoute
  '/(demo)/demo/sentry/testing': typeof demoDemoSentryTestingRoute
  '/(demo)/demo/start/api-request': typeof demoDemoStartApiRequestRoute
  '/(demo)/demo/start/server-funcs': typeof demoDemoStartServerFuncsRoute
  '/(demo)/example/guitars/$guitarId': typeof demoExampleGuitarsGuitarIdRoute
  '/(demo)/example/guitars/': typeof demoExampleGuitarsIndexRoute
  '/(demo)/demo/start/ssr/data-only': typeof demoDemoStartSsrDataOnlyRoute
  '/(demo)/demo/start/ssr/full-ssr': typeof demoDemoStartSsrFullSsrRoute
  '/(demo)/demo/start/ssr/spa-mode': typeof demoDemoStartSsrSpaModeRoute
  '/(demo)/demo/start/ssr/': typeof demoDemoStartSsrIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/discovery'
    | '/pricing'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/verify'
    | '/explore/$section'
    | '/library/profile'
    | '/movies/$movieId'
    | '/music/$musicid'
    | '/library'
    | '/movies'
    | '/demo/store'
    | '/demo/storybook'
    | '/demo/table'
    | '/demo/tanchat'
    | '/demo/tanstack-query'
    | '/demo'
    | '/home-demo'
    | '/demo/api/names'
    | '/demo/api/tanchat'
    | '/demo/api/tq-todos'
    | '/demo/sentry/testing'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/example/guitars/$guitarId'
    | '/example/guitars'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/discovery'
    | '/pricing'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/verify'
    | '/explore/$section'
    | '/library/profile'
    | '/movies/$movieId'
    | '/music/$musicid'
    | '/library'
    | '/movies'
    | '/demo/store'
    | '/demo/storybook'
    | '/demo/table'
    | '/demo/tanchat'
    | '/demo/tanstack-query'
    | '/demo'
    | '/home-demo'
    | '/demo/api/names'
    | '/demo/api/tanchat'
    | '/demo/api/tq-todos'
    | '/demo/sentry/testing'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/example/guitars/$guitarId'
    | '/example/guitars'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr'
  id:
    | '__root__'
    | '/'
    | '/discovery'
    | '/pricing'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/verify'
    | '/explore/$section'
    | '/library/profile'
    | '/movies/$movieId'
    | '/music/$musicid'
    | '/library/'
    | '/movies/'
    | '/(demo)/demo/store'
    | '/(demo)/demo/storybook'
    | '/(demo)/demo/table'
    | '/(demo)/demo/tanchat'
    | '/(demo)/demo/tanstack-query'
    | '/(demo)/demo/'
    | '/(demo)/home-demo/'
    | '/(demo)/demo/api/names'
    | '/(demo)/demo/api/tanchat'
    | '/(demo)/demo/api/tq-todos'
    | '/(demo)/demo/sentry/testing'
    | '/(demo)/demo/start/api-request'
    | '/(demo)/demo/start/server-funcs'
    | '/(demo)/example/guitars/$guitarId'
    | '/(demo)/example/guitars/'
    | '/(demo)/demo/start/ssr/data-only'
    | '/(demo)/demo/start/ssr/full-ssr'
    | '/(demo)/demo/start/ssr/spa-mode'
    | '/(demo)/demo/start/ssr/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DiscoveryRoute: typeof DiscoveryRoute
  PricingRoute: typeof PricingRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthVerifyRoute: typeof AuthVerifyRoute
  ExploreSectionRoute: typeof ExploreSectionRoute
  LibraryProfileRoute: typeof LibraryProfileRoute
  MoviesMovieIdRoute: typeof MoviesMovieIdRoute
  MusicMusicidRoute: typeof MusicMusicidRoute
  LibraryIndexRoute: typeof LibraryIndexRoute
  MoviesIndexRoute: typeof MoviesIndexRoute
  demoDemoStoreRoute: typeof demoDemoStoreRoute
  demoDemoStorybookRoute: typeof demoDemoStorybookRoute
  demoDemoTableRoute: typeof demoDemoTableRoute
  demoDemoTanchatRoute: typeof demoDemoTanchatRoute
  demoDemoTanstackQueryRoute: typeof demoDemoTanstackQueryRoute
  demoDemoIndexRoute: typeof demoDemoIndexRoute
  demoHomeDemoIndexRoute: typeof demoHomeDemoIndexRoute
  demoDemoApiNamesRoute: typeof demoDemoApiNamesRoute
  demoDemoApiTanchatRoute: typeof demoDemoApiTanchatRoute
  demoDemoApiTqTodosRoute: typeof demoDemoApiTqTodosRoute
  demoDemoSentryTestingRoute: typeof demoDemoSentryTestingRoute
  demoDemoStartApiRequestRoute: typeof demoDemoStartApiRequestRoute
  demoDemoStartServerFuncsRoute: typeof demoDemoStartServerFuncsRoute
  demoExampleGuitarsGuitarIdRoute: typeof demoExampleGuitarsGuitarIdRoute
  demoExampleGuitarsIndexRoute: typeof demoExampleGuitarsIndexRoute
  demoDemoStartSsrDataOnlyRoute: typeof demoDemoStartSsrDataOnlyRoute
  demoDemoStartSsrFullSsrRoute: typeof demoDemoStartSsrFullSsrRoute
  demoDemoStartSsrSpaModeRoute: typeof demoDemoStartSsrSpaModeRoute
  demoDemoStartSsrIndexRoute: typeof demoDemoStartSsrIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discovery': {
      id: '/discovery'
      path: '/discovery'
      fullPath: '/discovery'
      preLoaderRoute: typeof DiscoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movies/': {
      id: '/movies/'
      path: '/movies'
      fullPath: '/movies'
      preLoaderRoute: typeof MoviesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/': {
      id: '/library/'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/music/$musicid': {
      id: '/music/$musicid'
      path: '/music/$musicid'
      fullPath: '/music/$musicid'
      preLoaderRoute: typeof MusicMusicidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movies/$movieId': {
      id: '/movies/$movieId'
      path: '/movies/$movieId'
      fullPath: '/movies/$movieId'
      preLoaderRoute: typeof MoviesMovieIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/profile': {
      id: '/library/profile'
      path: '/library/profile'
      fullPath: '/library/profile'
      preLoaderRoute: typeof LibraryProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/$section': {
      id: '/explore/$section'
      path: '/explore/$section'
      fullPath: '/explore/$section'
      preLoaderRoute: typeof ExploreSectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify': {
      id: '/auth/verify'
      path: '/auth/verify'
      fullPath: '/auth/verify'
      preLoaderRoute: typeof AuthVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(demo)/home-demo/': {
      id: '/(demo)/home-demo/'
      path: '/home-demo'
      fullPath: '/home-demo'
      preLoaderRoute: typeof demoHomeDemoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(demo)/demo/': {
      id: '/(demo)/demo/'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof demoDemoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(demo)/demo/tanstack-query': {
      id: '/(demo)/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof demoDemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(demo)/demo/tanchat': {
      id: '/(demo)/demo/tanchat'
      path: '/demo/tanchat'
      fullPath: '/demo/tanchat'
      preLoaderRoute: typeof demoDemoTanchatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(demo)/demo/table': {
      id: '/(demo)/demo/table'
      path: '/demo/table'
      fullPath: '/demo/table'
      preLoaderRoute: typeof demoDemoTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(demo)/demo/storybook': {
      id: '/(demo)/demo/storybook'
      path: '/demo/storybook'
      fullPath: '/demo/storybook'
      preLoaderRoute: typeof demoDemoStorybookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(demo)/demo/store': {
      id: '/(demo)/demo/store'
      path: '/demo/store'
      fullPath: '/demo/store'
      preLoaderRoute: typeof demoDemoStoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(demo)/example/guitars/': {
      id: '/(demo)/example/guitars/'
      path: '/example/guitars'
      fullPath: '/example/guitars'
      preLoaderRoute: typeof demoExampleGuitarsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(demo)/example/guitars/$guitarId': {
      id: '/(demo)/example/guitars/$guitarId'
      path: '/example/guitars/$guitarId'
      fullPath: '/example/guitars/$guitarId'
      preLoaderRoute: typeof demoExampleGuitarsGuitarIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(demo)/demo/start/server-funcs': {
      id: '/(demo)/demo/start/server-funcs'
      path: '/demo/start/server-funcs'
      fullPath: '/demo/start/server-funcs'
      preLoaderRoute: typeof demoDemoStartServerFuncsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(demo)/demo/start/api-request': {
      id: '/(demo)/demo/start/api-request'
      path: '/demo/start/api-request'
      fullPath: '/demo/start/api-request'
      preLoaderRoute: typeof demoDemoStartApiRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(demo)/demo/sentry/testing': {
      id: '/(demo)/demo/sentry/testing'
      path: '/demo/sentry/testing'
      fullPath: '/demo/sentry/testing'
      preLoaderRoute: typeof demoDemoSentryTestingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(demo)/demo/api/tq-todos': {
      id: '/(demo)/demo/api/tq-todos'
      path: '/demo/api/tq-todos'
      fullPath: '/demo/api/tq-todos'
      preLoaderRoute: typeof demoDemoApiTqTodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(demo)/demo/api/tanchat': {
      id: '/(demo)/demo/api/tanchat'
      path: '/demo/api/tanchat'
      fullPath: '/demo/api/tanchat'
      preLoaderRoute: typeof demoDemoApiTanchatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(demo)/demo/api/names': {
      id: '/(demo)/demo/api/names'
      path: '/demo/api/names'
      fullPath: '/demo/api/names'
      preLoaderRoute: typeof demoDemoApiNamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(demo)/demo/start/ssr/': {
      id: '/(demo)/demo/start/ssr/'
      path: '/demo/start/ssr'
      fullPath: '/demo/start/ssr'
      preLoaderRoute: typeof demoDemoStartSsrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(demo)/demo/start/ssr/spa-mode': {
      id: '/(demo)/demo/start/ssr/spa-mode'
      path: '/demo/start/ssr/spa-mode'
      fullPath: '/demo/start/ssr/spa-mode'
      preLoaderRoute: typeof demoDemoStartSsrSpaModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(demo)/demo/start/ssr/full-ssr': {
      id: '/(demo)/demo/start/ssr/full-ssr'
      path: '/demo/start/ssr/full-ssr'
      fullPath: '/demo/start/ssr/full-ssr'
      preLoaderRoute: typeof demoDemoStartSsrFullSsrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(demo)/demo/start/ssr/data-only': {
      id: '/(demo)/demo/start/ssr/data-only'
      path: '/demo/start/ssr/data-only'
      fullPath: '/demo/start/ssr/data-only'
      preLoaderRoute: typeof demoDemoStartSsrDataOnlyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DiscoveryRoute: DiscoveryRoute,
  PricingRoute: PricingRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthVerifyRoute: AuthVerifyRoute,
  ExploreSectionRoute: ExploreSectionRoute,
  LibraryProfileRoute: LibraryProfileRoute,
  MoviesMovieIdRoute: MoviesMovieIdRoute,
  MusicMusicidRoute: MusicMusicidRoute,
  LibraryIndexRoute: LibraryIndexRoute,
  MoviesIndexRoute: MoviesIndexRoute,
  demoDemoStoreRoute: demoDemoStoreRoute,
  demoDemoStorybookRoute: demoDemoStorybookRoute,
  demoDemoTableRoute: demoDemoTableRoute,
  demoDemoTanchatRoute: demoDemoTanchatRoute,
  demoDemoTanstackQueryRoute: demoDemoTanstackQueryRoute,
  demoDemoIndexRoute: demoDemoIndexRoute,
  demoHomeDemoIndexRoute: demoHomeDemoIndexRoute,
  demoDemoApiNamesRoute: demoDemoApiNamesRoute,
  demoDemoApiTanchatRoute: demoDemoApiTanchatRoute,
  demoDemoApiTqTodosRoute: demoDemoApiTqTodosRoute,
  demoDemoSentryTestingRoute: demoDemoSentryTestingRoute,
  demoDemoStartApiRequestRoute: demoDemoStartApiRequestRoute,
  demoDemoStartServerFuncsRoute: demoDemoStartServerFuncsRoute,
  demoExampleGuitarsGuitarIdRoute: demoExampleGuitarsGuitarIdRoute,
  demoExampleGuitarsIndexRoute: demoExampleGuitarsIndexRoute,
  demoDemoStartSsrDataOnlyRoute: demoDemoStartSsrDataOnlyRoute,
  demoDemoStartSsrFullSsrRoute: demoDemoStartSsrFullSsrRoute,
  demoDemoStartSsrSpaModeRoute: demoDemoStartSsrSpaModeRoute,
  demoDemoStartSsrIndexRoute: demoDemoStartSsrIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
