/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as homeIndexRouteImport } from './routes/(home)/index'
import { Route as homePricingRouteImport } from './routes/(home)/pricing'
import { Route as homeDownloadRouteImport } from './routes/(home)/download'
import { Route as homeDiscoveryRouteImport } from './routes/(home)/discovery'
import { Route as authVerifyRouteImport } from './routes/(auth)/verify'
import { Route as authRegisterRouteImport } from './routes/(auth)/register'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as homeMusicIndexRouteImport } from './routes/(home)/music/index'
import { Route as homeMoviesIndexRouteImport } from './routes/(home)/movies/index'
import { Route as homeLibraryIndexRouteImport } from './routes/(home)/library/index'
import { Route as demoHomeDemoIndexRouteImport } from './routes/(demo)/home-demo/index'
import { Route as demoDemoIndexRouteImport } from './routes/(demo)/demo/index'
import { Route as adminSettingIndexRouteImport } from './routes/(admin)/setting/index'
import { Route as homeMusicMusicidRouteImport } from './routes/(home)/music/$musicid'
import { Route as homeMoviesMovieIdRouteImport } from './routes/(home)/movies/$movieId'
import { Route as homeLibraryProfileRouteImport } from './routes/(home)/library/profile'
import { Route as homeExploreSectionRouteImport } from './routes/(home)/explore/$section'
import { Route as homeArtistArtistidRouteImport } from './routes/(home)/artist/$artistid'
import { Route as demoDemoTanstackQueryRouteImport } from './routes/(demo)/demo/tanstack-query'
import { Route as demoDemoTanchatRouteImport } from './routes/(demo)/demo/tanchat'
import { Route as demoDemoTableRouteImport } from './routes/(demo)/demo/table'
import { Route as demoDemoStorybookRouteImport } from './routes/(demo)/demo/storybook'
import { Route as demoDemoStoreRouteImport } from './routes/(demo)/demo/store'
import { Route as demoDemoFormDemoRouteImport } from './routes/(demo)/demo/form-demo'
import { Route as demoExampleGuitarsIndexRouteImport } from './routes/(demo)/example.guitars/index'
import { Route as demoExampleGuitarsGuitarIdRouteImport } from './routes/(demo)/example.guitars/$guitarId'
import { Route as demoDemoStartServerFuncsRouteImport } from './routes/(demo)/demo/start.server-funcs'
import { Route as demoDemoStartApiRequestRouteImport } from './routes/(demo)/demo/start.api-request'
import { Route as demoDemoSentryTestingRouteImport } from './routes/(demo)/demo/sentry.testing'
import { Route as demoDemoApiTqTodosRouteImport } from './routes/(demo)/demo/api.tq-todos'
import { Route as demoDemoApiTanchatRouteImport } from './routes/(demo)/demo/api.tanchat'
import { Route as demoDemoApiNamesRouteImport } from './routes/(demo)/demo/api.names'
import { Route as demoDemoStartSsrIndexRouteImport } from './routes/(demo)/demo/start.ssr.index'
import { Route as demoDemoStartSsrSpaModeRouteImport } from './routes/(demo)/demo/start.ssr.spa-mode'
import { Route as demoDemoStartSsrFullSsrRouteImport } from './routes/(demo)/demo/start.ssr.full-ssr'
import { Route as demoDemoStartSsrDataOnlyRouteImport } from './routes/(demo)/demo/start.ssr.data-only'

const homeIndexRoute = homeIndexRouteImport.update({
  id: '/(home)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const homePricingRoute = homePricingRouteImport.update({
  id: '/(home)/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const homeDownloadRoute = homeDownloadRouteImport.update({
  id: '/(home)/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const homeDiscoveryRoute = homeDiscoveryRouteImport.update({
  id: '/(home)/discovery',
  path: '/discovery',
  getParentRoute: () => rootRouteImport,
} as any)
const authVerifyRoute = authVerifyRouteImport.update({
  id: '/(auth)/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const authRegisterRoute = authRegisterRouteImport.update({
  id: '/(auth)/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const homeMusicIndexRoute = homeMusicIndexRouteImport.update({
  id: '/(home)/music/',
  path: '/music/',
  getParentRoute: () => rootRouteImport,
} as any)
const homeMoviesIndexRoute = homeMoviesIndexRouteImport.update({
  id: '/(home)/movies/',
  path: '/movies/',
  getParentRoute: () => rootRouteImport,
} as any)
const homeLibraryIndexRoute = homeLibraryIndexRouteImport.update({
  id: '/(home)/library/',
  path: '/library/',
  getParentRoute: () => rootRouteImport,
} as any)
const demoHomeDemoIndexRoute = demoHomeDemoIndexRouteImport.update({
  id: '/(demo)/home-demo/',
  path: '/home-demo/',
  getParentRoute: () => rootRouteImport,
} as any)
const demoDemoIndexRoute = demoDemoIndexRouteImport.update({
  id: '/(demo)/demo/',
  path: '/demo/',
  getParentRoute: () => rootRouteImport,
} as any)
const adminSettingIndexRoute = adminSettingIndexRouteImport.update({
  id: '/(admin)/setting/',
  path: '/setting/',
  getParentRoute: () => rootRouteImport,
} as any)
const homeMusicMusicidRoute = homeMusicMusicidRouteImport.update({
  id: '/(home)/music/$musicid',
  path: '/music/$musicid',
  getParentRoute: () => rootRouteImport,
} as any)
const homeMoviesMovieIdRoute = homeMoviesMovieIdRouteImport.update({
  id: '/(home)/movies/$movieId',
  path: '/movies/$movieId',
  getParentRoute: () => rootRouteImport,
} as any)
const homeLibraryProfileRoute = homeLibraryProfileRouteImport.update({
  id: '/(home)/library/profile',
  path: '/library/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const homeExploreSectionRoute = homeExploreSectionRouteImport.update({
  id: '/(home)/explore/$section',
  path: '/explore/$section',
  getParentRoute: () => rootRouteImport,
} as any)
const homeArtistArtistidRoute = homeArtistArtistidRouteImport.update({
  id: '/(home)/artist/$artistid',
  path: '/artist/$artistid',
  getParentRoute: () => rootRouteImport,
} as any)
const demoDemoTanstackQueryRoute = demoDemoTanstackQueryRouteImport.update({
  id: '/(demo)/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const demoDemoTanchatRoute = demoDemoTanchatRouteImport.update({
  id: '/(demo)/demo/tanchat',
  path: '/demo/tanchat',
  getParentRoute: () => rootRouteImport,
} as any)
const demoDemoTableRoute = demoDemoTableRouteImport.update({
  id: '/(demo)/demo/table',
  path: '/demo/table',
  getParentRoute: () => rootRouteImport,
} as any)
const demoDemoStorybookRoute = demoDemoStorybookRouteImport.update({
  id: '/(demo)/demo/storybook',
  path: '/demo/storybook',
  getParentRoute: () => rootRouteImport,
} as any)
const demoDemoStoreRoute = demoDemoStoreRouteImport.update({
  id: '/(demo)/demo/store',
  path: '/demo/store',
  getParentRoute: () => rootRouteImport,
} as any)
const demoDemoFormDemoRoute = demoDemoFormDemoRouteImport.update({
  id: '/(demo)/demo/form-demo',
  path: '/demo/form-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const demoExampleGuitarsIndexRoute = demoExampleGuitarsIndexRouteImport.update({
  id: '/(demo)/example/guitars/',
  path: '/example/guitars/',
  getParentRoute: () => rootRouteImport,
} as any)
const demoExampleGuitarsGuitarIdRoute =
  demoExampleGuitarsGuitarIdRouteImport.update({
    id: '/(demo)/example/guitars/$guitarId',
    path: '/example/guitars/$guitarId',
    getParentRoute: () => rootRouteImport,
  } as any)
const demoDemoStartServerFuncsRoute =
  demoDemoStartServerFuncsRouteImport.update({
    id: '/(demo)/demo/start/server-funcs',
    path: '/demo/start/server-funcs',
    getParentRoute: () => rootRouteImport,
  } as any)
const demoDemoStartApiRequestRoute = demoDemoStartApiRequestRouteImport.update({
  id: '/(demo)/demo/start/api-request',
  path: '/demo/start/api-request',
  getParentRoute: () => rootRouteImport,
} as any)
const demoDemoSentryTestingRoute = demoDemoSentryTestingRouteImport.update({
  id: '/(demo)/demo/sentry/testing',
  path: '/demo/sentry/testing',
  getParentRoute: () => rootRouteImport,
} as any)
const demoDemoApiTqTodosRoute = demoDemoApiTqTodosRouteImport.update({
  id: '/(demo)/demo/api/tq-todos',
  path: '/demo/api/tq-todos',
  getParentRoute: () => rootRouteImport,
} as any)
const demoDemoApiTanchatRoute = demoDemoApiTanchatRouteImport.update({
  id: '/(demo)/demo/api/tanchat',
  path: '/demo/api/tanchat',
  getParentRoute: () => rootRouteImport,
} as any)
const demoDemoApiNamesRoute = demoDemoApiNamesRouteImport.update({
  id: '/(demo)/demo/api/names',
  path: '/demo/api/names',
  getParentRoute: () => rootRouteImport,
} as any)
const demoDemoStartSsrIndexRoute = demoDemoStartSsrIndexRouteImport.update({
  id: '/(demo)/demo/start/ssr/',
  path: '/demo/start/ssr/',
  getParentRoute: () => rootRouteImport,
} as any)
const demoDemoStartSsrSpaModeRoute = demoDemoStartSsrSpaModeRouteImport.update({
  id: '/(demo)/demo/start/ssr/spa-mode',
  path: '/demo/start/ssr/spa-mode',
  getParentRoute: () => rootRouteImport,
} as any)
const demoDemoStartSsrFullSsrRoute = demoDemoStartSsrFullSsrRouteImport.update({
  id: '/(demo)/demo/start/ssr/full-ssr',
  path: '/demo/start/ssr/full-ssr',
  getParentRoute: () => rootRouteImport,
} as any)
const demoDemoStartSsrDataOnlyRoute =
  demoDemoStartSsrDataOnlyRouteImport.update({
    id: '/(demo)/demo/start/ssr/data-only',
    path: '/demo/start/ssr/data-only',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/forgot-password': typeof authForgotPasswordRoute
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/verify': typeof authVerifyRoute
  '/discovery': typeof homeDiscoveryRoute
  '/download': typeof homeDownloadRoute
  '/pricing': typeof homePricingRoute
  '/': typeof homeIndexRoute
  '/demo/form-demo': typeof demoDemoFormDemoRoute
  '/demo/store': typeof demoDemoStoreRoute
  '/demo/storybook': typeof demoDemoStorybookRoute
  '/demo/table': typeof demoDemoTableRoute
  '/demo/tanchat': typeof demoDemoTanchatRoute
  '/demo/tanstack-query': typeof demoDemoTanstackQueryRoute
  '/artist/$artistid': typeof homeArtistArtistidRoute
  '/explore/$section': typeof homeExploreSectionRoute
  '/library/profile': typeof homeLibraryProfileRoute
  '/movies/$movieId': typeof homeMoviesMovieIdRoute
  '/music/$musicid': typeof homeMusicMusicidRoute
  '/setting': typeof adminSettingIndexRoute
  '/demo': typeof demoDemoIndexRoute
  '/home-demo': typeof demoHomeDemoIndexRoute
  '/library': typeof homeLibraryIndexRoute
  '/movies': typeof homeMoviesIndexRoute
  '/music': typeof homeMusicIndexRoute
  '/demo/api/names': typeof demoDemoApiNamesRoute
  '/demo/api/tanchat': typeof demoDemoApiTanchatRoute
  '/demo/api/tq-todos': typeof demoDemoApiTqTodosRoute
  '/demo/sentry/testing': typeof demoDemoSentryTestingRoute
  '/demo/start/api-request': typeof demoDemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof demoDemoStartServerFuncsRoute
  '/example/guitars/$guitarId': typeof demoExampleGuitarsGuitarIdRoute
  '/example/guitars': typeof demoExampleGuitarsIndexRoute
  '/demo/start/ssr/data-only': typeof demoDemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof demoDemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof demoDemoStartSsrSpaModeRoute
  '/demo/start/ssr': typeof demoDemoStartSsrIndexRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof authForgotPasswordRoute
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/verify': typeof authVerifyRoute
  '/discovery': typeof homeDiscoveryRoute
  '/download': typeof homeDownloadRoute
  '/pricing': typeof homePricingRoute
  '/': typeof homeIndexRoute
  '/demo/form-demo': typeof demoDemoFormDemoRoute
  '/demo/store': typeof demoDemoStoreRoute
  '/demo/storybook': typeof demoDemoStorybookRoute
  '/demo/table': typeof demoDemoTableRoute
  '/demo/tanchat': typeof demoDemoTanchatRoute
  '/demo/tanstack-query': typeof demoDemoTanstackQueryRoute
  '/artist/$artistid': typeof homeArtistArtistidRoute
  '/explore/$section': typeof homeExploreSectionRoute
  '/library/profile': typeof homeLibraryProfileRoute
  '/movies/$movieId': typeof homeMoviesMovieIdRoute
  '/music/$musicid': typeof homeMusicMusicidRoute
  '/setting': typeof adminSettingIndexRoute
  '/demo': typeof demoDemoIndexRoute
  '/home-demo': typeof demoHomeDemoIndexRoute
  '/library': typeof homeLibraryIndexRoute
  '/movies': typeof homeMoviesIndexRoute
  '/music': typeof homeMusicIndexRoute
  '/demo/api/names': typeof demoDemoApiNamesRoute
  '/demo/api/tanchat': typeof demoDemoApiTanchatRoute
  '/demo/api/tq-todos': typeof demoDemoApiTqTodosRoute
  '/demo/sentry/testing': typeof demoDemoSentryTestingRoute
  '/demo/start/api-request': typeof demoDemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof demoDemoStartServerFuncsRoute
  '/example/guitars/$guitarId': typeof demoExampleGuitarsGuitarIdRoute
  '/example/guitars': typeof demoExampleGuitarsIndexRoute
  '/demo/start/ssr/data-only': typeof demoDemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof demoDemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof demoDemoStartSsrSpaModeRoute
  '/demo/start/ssr': typeof demoDemoStartSsrIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/register': typeof authRegisterRoute
  '/(auth)/verify': typeof authVerifyRoute
  '/(home)/discovery': typeof homeDiscoveryRoute
  '/(home)/download': typeof homeDownloadRoute
  '/(home)/pricing': typeof homePricingRoute
  '/(home)/': typeof homeIndexRoute
  '/(demo)/demo/form-demo': typeof demoDemoFormDemoRoute
  '/(demo)/demo/store': typeof demoDemoStoreRoute
  '/(demo)/demo/storybook': typeof demoDemoStorybookRoute
  '/(demo)/demo/table': typeof demoDemoTableRoute
  '/(demo)/demo/tanchat': typeof demoDemoTanchatRoute
  '/(demo)/demo/tanstack-query': typeof demoDemoTanstackQueryRoute
  '/(home)/artist/$artistid': typeof homeArtistArtistidRoute
  '/(home)/explore/$section': typeof homeExploreSectionRoute
  '/(home)/library/profile': typeof homeLibraryProfileRoute
  '/(home)/movies/$movieId': typeof homeMoviesMovieIdRoute
  '/(home)/music/$musicid': typeof homeMusicMusicidRoute
  '/(admin)/setting/': typeof adminSettingIndexRoute
  '/(demo)/demo/': typeof demoDemoIndexRoute
  '/(demo)/home-demo/': typeof demoHomeDemoIndexRoute
  '/(home)/library/': typeof homeLibraryIndexRoute
  '/(home)/movies/': typeof homeMoviesIndexRoute
  '/(home)/music/': typeof homeMusicIndexRoute
  '/(demo)/demo/api/names': typeof demoDemoApiNamesRoute
  '/(demo)/demo/api/tanchat': typeof demoDemoApiTanchatRoute
  '/(demo)/demo/api/tq-todos': typeof demoDemoApiTqTodosRoute
  '/(demo)/demo/sentry/testing': typeof demoDemoSentryTestingRoute
  '/(demo)/demo/start/api-request': typeof demoDemoStartApiRequestRoute
  '/(demo)/demo/start/server-funcs': typeof demoDemoStartServerFuncsRoute
  '/(demo)/example/guitars/$guitarId': typeof demoExampleGuitarsGuitarIdRoute
  '/(demo)/example/guitars/': typeof demoExampleGuitarsIndexRoute
  '/(demo)/demo/start/ssr/data-only': typeof demoDemoStartSsrDataOnlyRoute
  '/(demo)/demo/start/ssr/full-ssr': typeof demoDemoStartSsrFullSsrRoute
  '/(demo)/demo/start/ssr/spa-mode': typeof demoDemoStartSsrSpaModeRoute
  '/(demo)/demo/start/ssr/': typeof demoDemoStartSsrIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/verify'
    | '/discovery'
    | '/download'
    | '/pricing'
    | '/'
    | '/demo/form-demo'
    | '/demo/store'
    | '/demo/storybook'
    | '/demo/table'
    | '/demo/tanchat'
    | '/demo/tanstack-query'
    | '/artist/$artistid'
    | '/explore/$section'
    | '/library/profile'
    | '/movies/$movieId'
    | '/music/$musicid'
    | '/setting'
    | '/demo'
    | '/home-demo'
    | '/library'
    | '/movies'
    | '/music'
    | '/demo/api/names'
    | '/demo/api/tanchat'
    | '/demo/api/tq-todos'
    | '/demo/sentry/testing'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/example/guitars/$guitarId'
    | '/example/guitars'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/verify'
    | '/discovery'
    | '/download'
    | '/pricing'
    | '/'
    | '/demo/form-demo'
    | '/demo/store'
    | '/demo/storybook'
    | '/demo/table'
    | '/demo/tanchat'
    | '/demo/tanstack-query'
    | '/artist/$artistid'
    | '/explore/$section'
    | '/library/profile'
    | '/movies/$movieId'
    | '/music/$musicid'
    | '/setting'
    | '/demo'
    | '/home-demo'
    | '/library'
    | '/movies'
    | '/music'
    | '/demo/api/names'
    | '/demo/api/tanchat'
    | '/demo/api/tq-todos'
    | '/demo/sentry/testing'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/example/guitars/$guitarId'
    | '/example/guitars'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr'
  id:
    | '__root__'
    | '/(auth)/forgot-password'
    | '/(auth)/login'
    | '/(auth)/register'
    | '/(auth)/verify'
    | '/(home)/discovery'
    | '/(home)/download'
    | '/(home)/pricing'
    | '/(home)/'
    | '/(demo)/demo/form-demo'
    | '/(demo)/demo/store'
    | '/(demo)/demo/storybook'
    | '/(demo)/demo/table'
    | '/(demo)/demo/tanchat'
    | '/(demo)/demo/tanstack-query'
    | '/(home)/artist/$artistid'
    | '/(home)/explore/$section'
    | '/(home)/library/profile'
    | '/(home)/movies/$movieId'
    | '/(home)/music/$musicid'
    | '/(admin)/setting/'
    | '/(demo)/demo/'
    | '/(demo)/home-demo/'
    | '/(home)/library/'
    | '/(home)/movies/'
    | '/(home)/music/'
    | '/(demo)/demo/api/names'
    | '/(demo)/demo/api/tanchat'
    | '/(demo)/demo/api/tq-todos'
    | '/(demo)/demo/sentry/testing'
    | '/(demo)/demo/start/api-request'
    | '/(demo)/demo/start/server-funcs'
    | '/(demo)/example/guitars/$guitarId'
    | '/(demo)/example/guitars/'
    | '/(demo)/demo/start/ssr/data-only'
    | '/(demo)/demo/start/ssr/full-ssr'
    | '/(demo)/demo/start/ssr/spa-mode'
    | '/(demo)/demo/start/ssr/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authLoginRoute: typeof authLoginRoute
  authRegisterRoute: typeof authRegisterRoute
  authVerifyRoute: typeof authVerifyRoute
  homeDiscoveryRoute: typeof homeDiscoveryRoute
  homeDownloadRoute: typeof homeDownloadRoute
  homePricingRoute: typeof homePricingRoute
  homeIndexRoute: typeof homeIndexRoute
  demoDemoFormDemoRoute: typeof demoDemoFormDemoRoute
  demoDemoStoreRoute: typeof demoDemoStoreRoute
  demoDemoStorybookRoute: typeof demoDemoStorybookRoute
  demoDemoTableRoute: typeof demoDemoTableRoute
  demoDemoTanchatRoute: typeof demoDemoTanchatRoute
  demoDemoTanstackQueryRoute: typeof demoDemoTanstackQueryRoute
  homeArtistArtistidRoute: typeof homeArtistArtistidRoute
  homeExploreSectionRoute: typeof homeExploreSectionRoute
  homeLibraryProfileRoute: typeof homeLibraryProfileRoute
  homeMoviesMovieIdRoute: typeof homeMoviesMovieIdRoute
  homeMusicMusicidRoute: typeof homeMusicMusicidRoute
  adminSettingIndexRoute: typeof adminSettingIndexRoute
  demoDemoIndexRoute: typeof demoDemoIndexRoute
  demoHomeDemoIndexRoute: typeof demoHomeDemoIndexRoute
  homeLibraryIndexRoute: typeof homeLibraryIndexRoute
  homeMoviesIndexRoute: typeof homeMoviesIndexRoute
  homeMusicIndexRoute: typeof homeMusicIndexRoute
  demoDemoApiNamesRoute: typeof demoDemoApiNamesRoute
  demoDemoApiTanchatRoute: typeof demoDemoApiTanchatRoute
  demoDemoApiTqTodosRoute: typeof demoDemoApiTqTodosRoute
  demoDemoSentryTestingRoute: typeof demoDemoSentryTestingRoute
  demoDemoStartApiRequestRoute: typeof demoDemoStartApiRequestRoute
  demoDemoStartServerFuncsRoute: typeof demoDemoStartServerFuncsRoute
  demoExampleGuitarsGuitarIdRoute: typeof demoExampleGuitarsGuitarIdRoute
  demoExampleGuitarsIndexRoute: typeof demoExampleGuitarsIndexRoute
  demoDemoStartSsrDataOnlyRoute: typeof demoDemoStartSsrDataOnlyRoute
  demoDemoStartSsrFullSsrRoute: typeof demoDemoStartSsrFullSsrRoute
  demoDemoStartSsrSpaModeRoute: typeof demoDemoStartSsrSpaModeRoute
  demoDemoStartSsrIndexRoute: typeof demoDemoStartSsrIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(home)/': {
      id: '/(home)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof homeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(home)/pricing': {
      id: '/(home)/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof homePricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(home)/download': {
      id: '/(home)/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof homeDownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(home)/discovery': {
      id: '/(home)/discovery'
      path: '/discovery'
      fullPath: '/discovery'
      preLoaderRoute: typeof homeDiscoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/verify': {
      id: '/(auth)/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof authVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/register': {
      id: '/(auth)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(home)/music/': {
      id: '/(home)/music/'
      path: '/music'
      fullPath: '/music'
      preLoaderRoute: typeof homeMusicIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(home)/movies/': {
      id: '/(home)/movies/'
      path: '/movies'
      fullPath: '/movies'
      preLoaderRoute: typeof homeMoviesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(home)/library/': {
      id: '/(home)/library/'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof homeLibraryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(demo)/home-demo/': {
      id: '/(demo)/home-demo/'
      path: '/home-demo'
      fullPath: '/home-demo'
      preLoaderRoute: typeof demoHomeDemoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(demo)/demo/': {
      id: '/(demo)/demo/'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof demoDemoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(admin)/setting/': {
      id: '/(admin)/setting/'
      path: '/setting'
      fullPath: '/setting'
      preLoaderRoute: typeof adminSettingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(home)/music/$musicid': {
      id: '/(home)/music/$musicid'
      path: '/music/$musicid'
      fullPath: '/music/$musicid'
      preLoaderRoute: typeof homeMusicMusicidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(home)/movies/$movieId': {
      id: '/(home)/movies/$movieId'
      path: '/movies/$movieId'
      fullPath: '/movies/$movieId'
      preLoaderRoute: typeof homeMoviesMovieIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(home)/library/profile': {
      id: '/(home)/library/profile'
      path: '/library/profile'
      fullPath: '/library/profile'
      preLoaderRoute: typeof homeLibraryProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(home)/explore/$section': {
      id: '/(home)/explore/$section'
      path: '/explore/$section'
      fullPath: '/explore/$section'
      preLoaderRoute: typeof homeExploreSectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(home)/artist/$artistid': {
      id: '/(home)/artist/$artistid'
      path: '/artist/$artistid'
      fullPath: '/artist/$artistid'
      preLoaderRoute: typeof homeArtistArtistidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(demo)/demo/tanstack-query': {
      id: '/(demo)/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof demoDemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(demo)/demo/tanchat': {
      id: '/(demo)/demo/tanchat'
      path: '/demo/tanchat'
      fullPath: '/demo/tanchat'
      preLoaderRoute: typeof demoDemoTanchatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(demo)/demo/table': {
      id: '/(demo)/demo/table'
      path: '/demo/table'
      fullPath: '/demo/table'
      preLoaderRoute: typeof demoDemoTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(demo)/demo/storybook': {
      id: '/(demo)/demo/storybook'
      path: '/demo/storybook'
      fullPath: '/demo/storybook'
      preLoaderRoute: typeof demoDemoStorybookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(demo)/demo/store': {
      id: '/(demo)/demo/store'
      path: '/demo/store'
      fullPath: '/demo/store'
      preLoaderRoute: typeof demoDemoStoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(demo)/demo/form-demo': {
      id: '/(demo)/demo/form-demo'
      path: '/demo/form-demo'
      fullPath: '/demo/form-demo'
      preLoaderRoute: typeof demoDemoFormDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(demo)/example/guitars/': {
      id: '/(demo)/example/guitars/'
      path: '/example/guitars'
      fullPath: '/example/guitars'
      preLoaderRoute: typeof demoExampleGuitarsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(demo)/example/guitars/$guitarId': {
      id: '/(demo)/example/guitars/$guitarId'
      path: '/example/guitars/$guitarId'
      fullPath: '/example/guitars/$guitarId'
      preLoaderRoute: typeof demoExampleGuitarsGuitarIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(demo)/demo/start/server-funcs': {
      id: '/(demo)/demo/start/server-funcs'
      path: '/demo/start/server-funcs'
      fullPath: '/demo/start/server-funcs'
      preLoaderRoute: typeof demoDemoStartServerFuncsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(demo)/demo/start/api-request': {
      id: '/(demo)/demo/start/api-request'
      path: '/demo/start/api-request'
      fullPath: '/demo/start/api-request'
      preLoaderRoute: typeof demoDemoStartApiRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(demo)/demo/sentry/testing': {
      id: '/(demo)/demo/sentry/testing'
      path: '/demo/sentry/testing'
      fullPath: '/demo/sentry/testing'
      preLoaderRoute: typeof demoDemoSentryTestingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(demo)/demo/api/tq-todos': {
      id: '/(demo)/demo/api/tq-todos'
      path: '/demo/api/tq-todos'
      fullPath: '/demo/api/tq-todos'
      preLoaderRoute: typeof demoDemoApiTqTodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(demo)/demo/api/tanchat': {
      id: '/(demo)/demo/api/tanchat'
      path: '/demo/api/tanchat'
      fullPath: '/demo/api/tanchat'
      preLoaderRoute: typeof demoDemoApiTanchatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(demo)/demo/api/names': {
      id: '/(demo)/demo/api/names'
      path: '/demo/api/names'
      fullPath: '/demo/api/names'
      preLoaderRoute: typeof demoDemoApiNamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(demo)/demo/start/ssr/': {
      id: '/(demo)/demo/start/ssr/'
      path: '/demo/start/ssr'
      fullPath: '/demo/start/ssr'
      preLoaderRoute: typeof demoDemoStartSsrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(demo)/demo/start/ssr/spa-mode': {
      id: '/(demo)/demo/start/ssr/spa-mode'
      path: '/demo/start/ssr/spa-mode'
      fullPath: '/demo/start/ssr/spa-mode'
      preLoaderRoute: typeof demoDemoStartSsrSpaModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(demo)/demo/start/ssr/full-ssr': {
      id: '/(demo)/demo/start/ssr/full-ssr'
      path: '/demo/start/ssr/full-ssr'
      fullPath: '/demo/start/ssr/full-ssr'
      preLoaderRoute: typeof demoDemoStartSsrFullSsrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(demo)/demo/start/ssr/data-only': {
      id: '/(demo)/demo/start/ssr/data-only'
      path: '/demo/start/ssr/data-only'
      fullPath: '/demo/start/ssr/data-only'
      preLoaderRoute: typeof demoDemoStartSsrDataOnlyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  authForgotPasswordRoute: authForgotPasswordRoute,
  authLoginRoute: authLoginRoute,
  authRegisterRoute: authRegisterRoute,
  authVerifyRoute: authVerifyRoute,
  homeDiscoveryRoute: homeDiscoveryRoute,
  homeDownloadRoute: homeDownloadRoute,
  homePricingRoute: homePricingRoute,
  homeIndexRoute: homeIndexRoute,
  demoDemoFormDemoRoute: demoDemoFormDemoRoute,
  demoDemoStoreRoute: demoDemoStoreRoute,
  demoDemoStorybookRoute: demoDemoStorybookRoute,
  demoDemoTableRoute: demoDemoTableRoute,
  demoDemoTanchatRoute: demoDemoTanchatRoute,
  demoDemoTanstackQueryRoute: demoDemoTanstackQueryRoute,
  homeArtistArtistidRoute: homeArtistArtistidRoute,
  homeExploreSectionRoute: homeExploreSectionRoute,
  homeLibraryProfileRoute: homeLibraryProfileRoute,
  homeMoviesMovieIdRoute: homeMoviesMovieIdRoute,
  homeMusicMusicidRoute: homeMusicMusicidRoute,
  adminSettingIndexRoute: adminSettingIndexRoute,
  demoDemoIndexRoute: demoDemoIndexRoute,
  demoHomeDemoIndexRoute: demoHomeDemoIndexRoute,
  homeLibraryIndexRoute: homeLibraryIndexRoute,
  homeMoviesIndexRoute: homeMoviesIndexRoute,
  homeMusicIndexRoute: homeMusicIndexRoute,
  demoDemoApiNamesRoute: demoDemoApiNamesRoute,
  demoDemoApiTanchatRoute: demoDemoApiTanchatRoute,
  demoDemoApiTqTodosRoute: demoDemoApiTqTodosRoute,
  demoDemoSentryTestingRoute: demoDemoSentryTestingRoute,
  demoDemoStartApiRequestRoute: demoDemoStartApiRequestRoute,
  demoDemoStartServerFuncsRoute: demoDemoStartServerFuncsRoute,
  demoExampleGuitarsGuitarIdRoute: demoExampleGuitarsGuitarIdRoute,
  demoExampleGuitarsIndexRoute: demoExampleGuitarsIndexRoute,
  demoDemoStartSsrDataOnlyRoute: demoDemoStartSsrDataOnlyRoute,
  demoDemoStartSsrFullSsrRoute: demoDemoStartSsrFullSsrRoute,
  demoDemoStartSsrSpaModeRoute: demoDemoStartSsrSpaModeRoute,
  demoDemoStartSsrIndexRoute: demoDemoStartSsrIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
